### ISSUE TITLE
Support `ignore_unmapped` in knn query

### ISSUE THREAD

**Issue by Firenze11** [opensearch-project/k-NN#1018]
**Is your feature request related to a problem? Please describe.**
I'm sending a knn query to a number of indices but they don't necessarily all have the knn field

```
GET my_index_prefix_*/_search
{"query": {"knn": {"embedding_256": {"k": 10, "vector": [......]}}}
```
fails with this error 

```
      {
        "shard": 0,
        "index": "my_index_prefix_123456",
        "node": "xxxxxx",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: Field 'embedding_256' is not knn_vector type.",
          "index": "my_index_prefix_123456",
          "index_uuid": "xxxxxx",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Field 'embedding_256' is not knn_vector type."
          }
        }
      }
```

**Describe the solution you'd like**
Like nested types, knn types can also have an `ignore_unmapped` field, so I can search among only the indices **with** this knn field. The query would be like

```
GET my_index_prefix_*/_search
{"query": {"knn": {"embedding_256": {"k": 10, "vector": [......], "ignore_unmapped": true}}}
```

**Describe alternatives you've considered**
Force adding an empty knn field to all indices. But that is troublesome.

**Comment by jmazanec15** [comment]
Seems like a pretty minor change: https://github.com/opensearch-project/OpenSearch/blob/60d272bc2fe875d7edd1e65ac87ac31999505ee1/server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java#L302-L311.

All we would have to do is add that logic around here: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java#L233-L235
