### ISSUE TITLE
Release version 1.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/k-NN#102]
Coming from [opensearch-build#567](https://github.com/opensearch-project/opensearch-build/issues/567), release version 1.2. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] Create, update, triage and label all features and issues targeted for this release with `v1.2.0`.

### CI/CD

- [x] Increment version on main to `1.2.0.0`.
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).

### Pre-Release

- [x] Branch and build from a `1.2` branch.
- [x] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).
- [x] Feature complete, pencils down.
- [x] Fix bugs that target this release.

### Release

- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes.
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [x] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [x] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-plugins/templates/release.md).
- [x] Conduct a postmortem, and publish its results.

**Comment by jmazanec15** [comment]
We need to make 1 more change #151. I will submit a PR to resolve this soon.

**Comment by jmazanec15** [comment]
Addressed in #191 and #192. Rest of changes will be bug fixes.

**Comment by naveentatikonda** [comment]
The release tag is created. If there are any callouts related to retrospective(postmortem), it will be added to this issue
https://github.com/opensearch-project/opensearch-build/issues/880
