### ISSUE TITLE
[FEATURE] Use the Lucene Distance Calculation Function in Script Scoring for doing exact search

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/k-NN#1032]
**Is your feature request related to a problem?**
No.

**What solution would you like?**
Currently in K-NN plugin we are using the custom functions to do the [distance calculation](https://github.com/opensearch-project/k-NN/blob/581faddf10792f7c19b7f4bb9f9deb6f8e77de63/src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java#L151-L167), with Lucene coming up with the support of SIMD we should use Lucene functions(https://github.com/apache/lucene/blob/branch_9_7/lucene/core/src/java/org/apache/lucene/util/VectorUtil.java).

**What alternatives have you considered?**
NA

**Do you have any additional context?**
NA

**Comment by TrungBui59** [comment]
Hi @navneet1v  and @vamshin, are you guys still working on this issue? If not, can I take over it?

**Comment by navneet1v** [comment]
@TrungBui59 no one is working on this feature. You can pick this up.

**Comment by PTheocharis** [comment]
Hello, can I try this issue as well?

**Comment by navneet1v** [comment]
> Hello, can I try this issue as well?

Yes you can. You can actually use the code from the PR and take it forward.

**Comment by PTheocharis** [comment]
I am a beginner in programming, do you think I can handle this? I am willing to put in the appropriate work

**Comment by navneet1v** [comment]
> I am a beginner in programming, do you think I can handle this? I am willing to put in the appropriate work

I won't recommend then picking up this issue then

**Comment by navneet1v** [comment]
Similar issue: https://github.com/opensearch-project/k-NN/issues/617

**Comment by jmazanec15** [comment]
Addressed in https://github.com/opensearch-project/k-NN/pull/1699
