### ISSUE TITLE
Add support for Java SDK 21.x

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/k-NN#1041]
**What is the bug?**
When using JDK 21 (21.0.1-amzn if sdk manager is used to manage JDKs) to build plugin I'm receiving errors saying current gradle version is incompatible with java 21.

Plugin needs to add support for that version in main branch, it's already set as default for distribution builds in corresponding build package in core : https://github.com/opensearch-project/opensearch-build/blob/main/manifests/3.0.0/opensearch-3.0.0.yml#L9

**How can one reproduce the bug?**
1. Install JDK 21. if you're using sdkman 
```
sdk install java 21.0.1-amzn
sdk use java 21.0.1-amzn
``` 
2. Run ``` ./gradlew compileJava ```
3. Build fails with error:
```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'opensearch-knn'.
> Could not open proj generic class cache for build file '/k-NN/build.gradle' (/.gradle/caches/7.6.1/scripts/6sy3xxd4if918xuaxzupspk2g).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65
```

**What is your host/environment?**
 - OS: Linux and Mac
 - main branch
 - Java 21.0.1 (21.0.1-amzn)

**Comment by martin-gaievski** [comment]
This issue isn't relevant anymore, we need to aim for JDK21, it's what core OpenSearch supports now and this will be an LTS release (20 is non-LTS). I'm updating issue description

**Comment by jmazanec15** [comment]
Covered in #1288. Closing
