### ISSUE TITLE
[FEATURE] Ensure the GIthub workflow pull docker image used by infra build

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/k-NN#1042]
**Is your feature request related to a problem?**
Ensure the GIthub workflow uses docker images that are used during the infra build for running integration tests. 
This is to make sure, integration tests are run on same environment as that of infra build and help catch issues early. WE recently noticed such discrepancy with GCC version incompatibility when FAISS library got upgraded which required more upgraded version of GCC 

**What solution would you like?**
k-NN GIthub workflow should pull docker images of build team instead of latest Ubuntu version

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by navneet1v** [comment]
Closing the issue as the changes are merged in all the respective branches.
