### ISSUE TITLE
[Benchmarking] Create single-node benchmarking docker application

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#1053]
## Problem

Currently, we have [2 tools](https://github.com/opensearch-project/k-NN/tree/main/benchmarks) that can be used to benchmark the plugin. These tools are very robust. You can just point them at a separately provisioned cluster and get performance results. 

However, this approach has a few downsides:
1. Effort is required to separately provision a cluster - this adds up over time
2. Effort is required to setup the client for benchmarking - this adds up over time
3. Differences in server environment may cause differences in performance results. For instance, a server that has twice as many CPUs will most likely be faster. Or, a server that is 3 generations newer, may be faster as well.
4. Difference in client configuration may make results not comparable. i.e. network configuration with respect to server, resources available, etc. 

Further, when trying to compare different algorithm configurations (i.e. #946 NSG vs. HNSW), we do not need to use multi-node clusters because we are not making changes that impact the distributed nature of the system. 

## Proposal

The proposal is to use docker containers through docker-compose on a single machine to create an easy to run performance benchmark, completely encompassed.

![single-node-perf-test](https://github.com/opensearch-project/k-NN/assets/19438237/f9e6b321-dc45-4772-8706-afbf4f01ec05)

The server environment:
1. Based on the corresponding versions staging dockerfile: https://hub.docker.com/r/opensearchstaging/opensearch
2. Use [multi-stage docker build](https://docs.docker.com/build/building/multi-stage/)to build custom plugin with https://hub.docker.com/r/opensearchstaging/ci-runner/tags and then copy it into corresponding opensearch image
3. limit the num of cpus and memory via [docker compose](https://docs.docker.com/compose/compose-file/compose-file-v3/#resources)

The client environment: 
1. Use rocky linux docker image
2. install perf-tool/osb in image
3. be configured to use custom workload params
4. limit the num of cpus and memory via [docker compose](https://docs.docker.com/compose/compose-file/compose-file-v3/#resources)

The docker-compose setup would:
1. Bring up the OpenSearch node with the custom plugin
2. Bring up the client instance
3. Run the client instance test against the OpenSearch node once it is confirmed up and running
4. Collect opensearch node telemetry (docker stats or rss usage, etc.)
5. Serialize results somewhere on the node

So, ideally, a user could just configure their workload and the data they want to use, and then execute docker-compose up on the machine and check back later and get the results.

In order to effectively compare results, the underlying hardware and backing disk type would still need to be fixed. For this, we could provide recommendation on cpu count and memory available and disk type.

**Comment by luyuncheng** [comment]
I am working on the benchmark with different algorithm, so i think docker-compose is a good idea to simplified benchmark environment in single-node benchmark. 

@jmazanec15 when benchmark configuration changed frequently , i have some ways to do it.

> Use [multi-stage docker build](https://docs.docker.com/build/building/multi-stage/)to build custom plugin with https://hub.docker.com/r/opensearchstaging/ci-runner/tags and then copy it into corresponding opensearch image

i mapped machine release directory into docker, and run reinstall knn plugin which in step1's image.

> install perf-tool/osb in image

i mapped machine perf-tool/osb directory into docker, and run benchmark with different configuration.

**Comment by luyuncheng** [comment]
> Would you be able to share any scripts? Also, how/where are you compiling the plugin? 

let me simplified my script and create pr for this issue

**Comment by luyuncheng** [comment]
i try to use image : opensearchstaging/ci-runner:ci-runner-rockylinux8-opensearch-build-v4 as client base image, but i found it not include requirements python modules in `perf-tool` and `osb`

@jmazanec15  Do you have any public image that i can use with opensearch prefix hub that installed all needed python modules

**Comment by jmazanec15** [comment]
@luyuncheng To get the perf-tool and osb, I would checkout this `git` repo and `pip install -r requirements.txt`. References for this setup are here:
1. https://github.com/opensearch-project/k-NN/tree/main/benchmarks/perf-tool#install-prerequisites
2. https://github.com/opensearch-project/k-NN/tree/main/benchmarks/perf-tool#install-prerequisites

**Comment by jmazanec15** [comment]
Thanks @luyuncheng, apologies for delay I was on vacation last week. Let me take a look.

**Comment by jmazanec15** [comment]
Closing for now. I implemented this which can be built on top of: https://github.com/jmazanec15/opensearch-knn-single-node-experiments. I dont think we need to add to repo
