### ISSUE TITLE
[FEATURE] [k-NN] Lucene Engine with SIMD support

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/k-NN#1062]
**Is your feature request related to a problem?**
Related to https://github.com/opensearch-project/OpenSearch/issues/9423

**Comment by heemin32** [comment]
I have done more testing regarding k-NN feature with different platforms and data set. SIMD improves both indexing and query latency significantly across various data dimensions and sizes.

Cluster configuration: 3 leader nodes (c5.xlarge), 1 data nodes (r5.8xlarge, for arm r6g.8xlarge is used), 16 shards
Test client: c5.4xlarge, 10 threads
OpenSearch version: 2.9.0

**Data: 128 dimendions, 62.5M**
Ingest latency
  | lucene | lucene-simd | faiss | nmslib | lucene-arm | lucene-arm-simd
-- | -- | -- | -- | -- | -- | --
p50 (ms)| 178.11421 | 122.30828 (&darr;31%) | 33.20409 | 32.69062 | 122.17994 | 96.55073 (&darr;21%)
p90 (ms)| 274.55679 | 209.68928 (&darr;24%)| 55.89496 | 59.54174 | 217.74488 | 173.76887 (&darr;20%)
p99 (ms)| 360.08076 | 371.0854 (&uarr;3%)| 136.11067 | 142.8995 | 308.54483 | 366.9349 (&uarr;20%)


Query latency
  | lucene | lucene-simd | faiss | nmslib | lucene-arm | lucene-arm-simd
-- | -- | -- | -- | -- | -- | --
p50 (ms)| 25.46449 | 21.36737 (&darr;16%)| 19.91484 | 12.67667 | 22.23088 | 18.52915 (&darr;17%)
p90 (ms)| 32.10869 | 27.49935 (&darr;14%)| 22.70937 | 15.81869 | 28.28701 | 23.47646 (&darr;17%)
p99 (ms)| 38.6863 | 34.31535 (&darr;11%)| 28.61526 | 21.55276 | 34.01487 | 29.16956 (&darr;14%)


Time taken to force merge after indexing
  | lucene | lucene-simd | faiss | nmslib | lucene-arm | lucene-arm-simd
-- | -- | -- | -- | -- | -- | --
Merge time(hours) | 51.2 | 32.4 (&darr;37%)| 45.2 | 54.4 | 64.1 | 38.9 (&darr;39%)


**Data: 768 dimendions, 10M**
Ingest latency
  | lucene | lucene-simd | faiss | nmslib | lucene-arm | lucene-arm-simd
-- | -- | -- | -- | -- | -- | --
p50 (ms)| 330.42268 | 162.81989 (&darr;51%)| 45.58239 | 44.23989 | 222.11812 | 157.54088 (&darr;29%)
p90 (ms)| 473.48127 | 301.78705 (&darr;36%)| 160.51715 | 159.05736 | 429.0347 | 414.04998 (&darr;3%)
p99 (ms)| 631.20325 | 628.94332 (&darr;0%)| 2043.30716 | 2067.34907 | 711.63805 | 697.69039 (&darr;2%)




Query latency
  | lucene | lucene-simd | faiss | nmslib | lucene-arm | lucene-arm-simd
-- | -- | -- | -- | -- | -- | --
p50 (ms)| 56.85642 | 39.89531 (&darr;30%)| 27.12591 | 28.30539 | 44.72728 | 36.15098 (&darr;19%)
p90 (ms)| 67.9561 | 50.22711 (&darr;26%)| 34.21036 | 35.30814 | 56.28556 | 46.84457 (&darr;17%)
p99 (ms)| 78.86851 | 60.37412 (&darr;23%)| 41.48554 | 43.02242 | 67.96228 | 57.9375 (&darr;15%)

**Comment by binarymax** [comment]
@heemin32 Thanks for this analysis!  Do by any chance have merge time for the second 768-Dim dataset?  Also if you have some code that lets us replicate these benchmarks that would be really helpful!

**Comment by binarymax** [comment]
Thanks so much for the detailed response, this is very helpful!

**Comment by heemin32** [comment]
Update to JDK21 is completed in OpenSearch 2.12. https://github.com/opensearch-project/OpenSearch/pull/11003
