### ISSUE TITLE
Fix Secure Cluster github actions for K-NN plugin

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/k-NN#1067]
### Description
Currently the github action to test the k-NN plugin integ tests on the Secure cluster is failing. Creating this github issue to track the fix for that action.

https://github.com/opensearch-project/k-NN/actions/workflows/test_security.yml

**Comment by jmazanec15** [comment]
Somewhat related to #901

**Comment by jmazanec15** [comment]
Closing this should be fixed with #1307
