### ISSUE TITLE
Searching for irrelevant data also returns results

### ISSUE THREAD

**Issue by savanbthakkar** [opensearch-project/k-NN#1195]
@savanbthakkar even with neural plugin this experience of irrelevant results will come because neural underline uses K-NN plugin.

There is no in build solution for this as of now. I would recommend converting this issue as a feature request, so that it can picked up.

_Originally posted by @navneet1v in https://github.com/opensearch-project/k-NN/issues/994#issuecomment-1735838708_

**Comment by navneet1v** [comment]
@savanbthakkar The issue: https://github.com/opensearch-project/k-NN/issues/994 is already marked as a feature. So I think either you can do +1 on that issue. Would like to avoid creating duplicate issues.
