### ISSUE TITLE
[BUG] Inner Hits for nested knn search always 1

### ISSUE THREAD

**Issue by Junaid986** [opensearch-project/k-NN#1270]
**What is the bug?**
A clear and concise description of the bug.

Tried putting knn vector inside a nested object since the use case need to embed large passages on the same document. Tried a nested knn query,

GET document_index/_search
{
   "query": {
      "nested": {
         "path": "chunk_embeddings",
         "query": {
              "chunk_embeddings.embedding": {
                   "vector": [....], _# a 384 dim vector_ 
                   "k": 10
              }
          },
         "inner_hits": {
             "size": 5
         }
      }
   }
}

The inner hits however is always 1. No more matchers to nested embeddings come up.

**How can one reproduce the bug?**
1. Create and index with nested knn vectors.
2. Do a nested knn query.
3. Inner hits always 1.

**What is the expected behavior?**
i would expect more number of inner hits so that i can find increase relavence of documents with higher knn matches

**What is your host/environment?**
 - OS: AWS Opensearch Managed cluster
 - Version 2.5
 - Plugins knn

**Do you have any screenshots?**
Apologies. This is in a sandboxed environment.

**Comment by Junaid986** [comment]
Setting "score_mode" resolved the issue.

**Comment by heemin32** [comment]
@Junaid986 Is the issue resolved after setting "score_mode"? Could you close the issue then?
