### ISSUE TITLE
[BUG] K-NN build failed on main branch with error: cannot find symbol import org.apache.lucene.codecs.lucene95.Lucene95HnswVectorsFormat;

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/k-NN#1382]
**What is the bug?**
Build K-NN is failed on main branch with the error:
```
/tmp/tmpxfw8bw22/k-NN/src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java:14: error: cannot find symbol
import org.apache.lucene.codecs.lucene95.Lucene95Codec;
> Task :compileJava FAILED
                                        ^
  symbol:   class Lucene95Codec
  location: package org.apache.lucene.codecs.lucene95
/tmp/tmpxfw8bw22/k-NN/src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java:8: error: cannot find symbol
import org.apache.lucene.codecs.lucene95.Lucene95HnswVectorsFormat;
                                        ^
  symbol:   class Lucene95HnswVectorsFormat
  location: package org.apache.lucene.codecs.lucene95
2 errors
```

This seems related to the new commit in opensearch core: https://github.com/opensearch-project/OpenSearch/commit/4a42150ba0cbf10022797c038f35faaea2f548f6

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ruanyl** [comment]
PR opened: https://github.com/opensearch-project/k-NN/pull/1383

**Comment by naveentatikonda** [comment]
Lucene Codec is bumped up, these import statements have been fixed and CI is succeeding. So, closing this issue.
