### ISSUE TITLE
Scores with dot product differ with exact score versus approximate score for native engines

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#1396]
## Description

For ANN search with filtering, we take a decision whether to just score all the docs or to run the ANN search. The problem with this approach is that we use Lucene distance function to score exact, while we use our own space type to score the results coming from the libraries ANN methods.

So, for a raw negative dot product score of -1,
1. ANN implementation will return 2: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/SpaceType.java#L70-L75
2. Exact will return a score of 1: https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/VectorSimilarityFunction.java#L55

## Desired solution

Scoring should be consistent. We should either use our own function to score or update to Lucene's MAX_IP distance function:
 https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/VectorSimilarityFunction.java#L87-L96

**Comment by jmazanec15** [comment]
> I also faced this issue, and this issue is mainly happens for inner_product right?

L2 should not have this problem, given we use same translation. 

> can we move towards using the Lucene based scoring for our exact search too? Given that with newer JDK we will start to use vector APIs also.

The issue isnt related to script scoring. It is that we are using Lucene distance functions for the calculations when we switch to exact with filtering. That being said, this issue will be resolved via switching to MAX_INNER_PRODUCT score

**Comment by theahura** [comment]
@jmazanec15 can you provide more documentation on what MAX INNER PRODUCT is and how it's set? I couldn't find anything easily just from a straightforward Google search

**Comment by navneet1v** [comment]
Can we close this issue now as the feature is pushed and will be released in 2.13
