### ISSUE TITLE
[BUG] Incorrect `faiss::IDSelectorBitmap` size in `faiss_wrapper.cpp`

### ISSUE THREAD

**Issue by ErikML** [opensearch-project/k-NN#1435]
**What is the bug?**
The faiss::IDSelectorBitmap is given the incorrect size. It is created as `new faiss::IDSelectorBitmap(filterIdsLength, bitmap.data())`. It should be created as `new faiss::IDSelectorBitmap(bitsetArraySize, bitmap.data())`.

In particular, this can cause faiss to incorrectly filter valid candidates when `filterIdsLength < bitsetArraySize`, as faiss rejects all candidates with ids larger than the `IDSelectorBitmap` size.

**How can one reproduce the bug?**

Create a filter where the number of elements and `maxIdValue` satisfies `maxIdValue / (8 * sizeof(faiss::idx_t)) < filterIdsLength < maxIdValue / 8`. Also make the element with the largest id the element with the highest score

This should trigger the bitmap filter and also make the bitmap size smaller than the number of entries. We don't return the highest scoring element even if faiss considers it because faiss filters it out.

**What is the expected behavior?**
Faiss should return the highest scoring element if it is considered.

**What is your host/environment?**
OS 2.11.0 with k-NN plugin 2.11.0.0.

**Do you have any screenshots?**
![FaissFilterRun](https://github.com/opensearch-project/k-NN/assets/4176228/a09db1ec-768b-47ef-ba89-ef96c11cb063)

**Do you have any additional context?**
No.

**Comment by heemin32** [comment]
If merged, this PR will resolve the issue. https://github.com/opensearch-project/k-NN/pull/1402

**Comment by ErikML** [comment]
It is also possible to over-read the buffer when `filterIdsLength` is larger than `bitsetArraySize`. This can allow returning datapoints that do not satisfy the filter.
![FilterBufferOverrun](https://github.com/opensearch-project/k-NN/assets/4176228/7838f367-02a1-4729-9870-ab6b8cd82532)

**Comment by heemin32** [comment]
Raised a [PR](https://github.com/opensearch-project/k-NN/pull/1444) to push the fix in 2.12 release.
