### ISSUE TITLE
[BUG] KNNCodecService is incompatible with Lucene best_compression Codec Mode

### ISSUE THREAD

**Issue by nknize** [opensearch-project/k-NN#146]
The current [KNN87Codec](https://github.com/opensearch-project/k-NN/blob/d7c55e9bdbc37d71a714569c9f37755053781c7d/src/main/java/org/opensearch/knn/index/codec/KNN87Codec/KNN87Codec.java#L81) uses a Delegate pattern for all Field Formats except `DocValues` and `CompoundFormat`. The problem with this delegate is that it always returns the default `LUCENE_87` format loaded through SPI making it incompatible with `best_compression` option available through the [index_settings](https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/create-index/#index-settings) configuration.

What this means to the end user is a misleading / unexpected behavior in the following situation:

```
"settings" : {
  "index" : {
    "codec" : "best_compression",
    "knn" : "true"
  }
} 
```

When `knn` is set to `true` the [KNNCodecService](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/plugin/KNNCodecService.java) is hot swapped in place of the default CodecService. As seen in the code the KNNCodecService [always returns](https://github.com/opensearch-project/k-NN/blob/d7c55e9bdbc37d71a714569c9f37755053781c7d/src/main/java/org/opensearch/knn/plugin/KNNCodecService.java#L52) `KNN87Codec.KNN_87` which uses the delegate pattern as described above. This means `index.codec` parameter value will be silently ignored  since the `name` is ignored in the `codec(String name)` overridden method.

Users will think they get `best_compression` on their fields but, sike, they won't. This is not a good experience and should be fixed so that (at minimum) the `best_compression` mode can be passed to the `KNNCodecService` giving the users the option to use compression on any fields other than compound and docValues formats. 

Documentation should also be updated to provide full transparency of codec behavior.

**Comment by jmazanec15** [comment]
One possible solution is to keep the delegate pattern, but change [the codec lookup code](https://github.com/opensearch-project/k-NN/blob/d7c55e9bdbc37d71a714569c9f37755053781c7d/src/main/java/org/opensearch/knn/plugin/KNNCodecService.java#L52) to this:

```
@Override
public Codec codec(String name) {
    return new KNN87Codec(super.codec(name));
}
```

Then, the KNN87Codec class could have 2 constructors:
```
public KNN87Codec() {
    this(new Lucene87Codec());
}

public KNN87Codec(Codec delegate) {
    super(KNN_87, delegate);
    this.docValuesFormat =  new KNN80DocValuesFormat();
    this.perFieldDocValuesFormat = new PerFieldDocValuesFormat() {
        @Override
        public DocValuesFormat getDocValuesFormatForField(String field) {
            return docValuesFormat;
        }
    };
    this.compoundFormat = new KNN80CompoundFormat();
}
```

The first constructor prevents SPI from breaking. The issue with this approach, however, is that any call to `Codec.forName` would result in the default Lucene87 codec being used. Outside of the CodecService, I do not see this call being made in OpenSearch. However, when I tried to remove KNNCodec87 from SPI, the tests produced an error because Lucene internally called Codec.forName with the KNN Codec:
```
failure [IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'KNN87Codec' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene87, Lucene70, Lucene80, Lucene84, Lucene86, KNN80Codec, KNN84Codec, KNN86Codec]]], markAsStale [true]]
?  java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'KNN87Codec' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene87, Lucene70, Lucene80, Lucene84, Lucene86, KNN80Codec, KNN84Codec, KNN86Codec]
?       at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.apache.lucene.codecs.Codec.forName(Codec.java:116) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:445) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:356) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.opensearch.index.engine.CombinedDeletionPolicy.getDocCountOfCommit(CombinedDeletionPolicy.java:158) ~[opensearch-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
?       at org.opensearch.index.engine.CombinedDeletionPolicy.onCommit(CombinedDeletionPolicy.java:127) ~[opensearch-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
?       at org.apache.lucene.index.IndexFileDeleter.checkpoint(IndexFileDeleter.java:533) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:3822) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3778) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3728) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
?       at org.opensearch.index.engine.InternalEngine.commitIndexWriter(InternalEngine.java:2767) ~[opensearch-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
```

So, Im wondering if it is just not possible to correctly set the delegate without hard coding it in a no arg constructor. If this is the case, the next solution I can think of is somewhat brute force (but potentially necessary to work with SPI): Create 1 codec per potential delegate
1. KNN87Codec_best_compression
2. KNN87Codec_default

@nknize @saratvemulapalli would you be able to provide your thoughts on the 2 approaches above?
