### ISSUE TITLE
[BUG] gradle build calls multiple `Task :test` tasks 

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/k-NN#1468]
**What is the bug?**

Found the following bug when working on [2.12.0 release](https://github.com/opensearch-project/opensearch-build/issues/4115), trying to build k-NN on my local.

When running the `./gradlew build --no-daemon --refresh-dependencies -x integTest -DskipTests=true -Dopensearch.version=2.12.0 -Dbuild.snapshot=false -Dbuild.version_qualifier=` part of the [build script](https://github.com/opensearch-project/k-NN/blob/main/scripts/build.sh#L121), multiple `Task :test` are executed, looks to me like the `-x integTest` is not honored. Explore adding `-x test` https://github.com/coditory/gradle-integration-test-plugin/blob/master/README.md.

Having this bug the k-NN build fails with failing flaky tests, `org.opensearch.knn.index.KNNSettingsTests > testGetEfSearch_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed FAILED`

```
Tests with failures:
 - org.opensearch.knn.index.KNNSettingsTests.testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed

480 tests completed, 1 failed, 2 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.
``` 

**How can one reproduce the bug?**
Clone the build repo https://github.com/opensearch-project/opensearch-build and run `./build.sh manifests/2.12.0/opensearch-2.12.0.yml --component k-NN `

**What is the expected behavior?**
The build should just focus on building the k-NN and not run tests as part of the build, the tests should be executed when called `./gradlew integTest` or `./gradlew test`.

@peterzhuamazon @bbarani @naveentatikonda @navneet1v @vamshin

**Comment by heemin32** [comment]
Same issue as https://github.com/opensearch-project/k-NN/issues/1392
