### ISSUE TITLE
[Enhancement][Build-Time] Remove conversion of KNN Field to string if stored Fields not required

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/k-NN#1598]
### Description
While doing some benchmarks with Opensearch k-NN. I see that there is time going in to convert the kNN field to String even when storedFields is marked as false. On doing deep-dive I found out that, we convert the field to the string and then check if stored field is set as true or false.

Code ref:
https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java#L575

Here `point.toString` will convert the object to string which is expensive operation in high dimensionality use cases. 

Refer the Flame graph for the same for Vector dimension: 1536 ingestion

![Screenshot 2024-04-08 at 12 58 58 PM](https://github.com/opensearch-project/k-NN/assets/6162415/0da20cef-f9a2-41e9-b252-753ea7ed680b)

**Comment by navneet1v** [comment]
The fix for the issue is pretty simple rather than doing toString we just need to pass the VectorField to the underline function.

**Comment by navneet1v** [comment]
Resolving the issue as the PR is merged.

**Comment by jmazanec15** [comment]
@navneet1v for the flame graph above, what was the setup? Trying to understand impact on ingestion
