### ISSUE TITLE
[BUG] ignore_unmapped check is always true in 2.x branch

### ISSUE THREAD

**Issue by junqiu-lei** [opensearch-project/k-NN#1629]
**What is the bug?**
When validate "ignore_unmapped", [here](https://github.com/opensearch-project/k-NN/blob/2.x/src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java#L270) it need to check if it equals currentFieldName instead of string value “ignore_unmapped”, the issue occurs in 2.x branch since https://github.com/opensearch-project/k-NN/pull/1152.

**Comment by junqiu-lei** [comment]
@ryanbogan Could you help to take a look?

**Comment by ryanbogan** [comment]
Looking into it
