### ISSUE TITLE
Remove duplicated parseCreateField in LuceneFieldMapper

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#1632]
## Description

Right now, we duplicate pretty closely the logic for parseCreateField in the LuceneFieldMapper that we do in KNNVectorFieldMapper:
1. https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java#L79-L123
2. https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java#L547-L583

The difference is that LuceneFieldMapper will create a KnnVectorField while the KNNVectorFieldMapper will create a VectorField. Im thinking we can simplify this to implement one parseCreateField and delegate based on engine type.

**Comment by navneet1v** [comment]
@jmazanec15 do you see any reason why we have duplicated this code? I took a look at the code and the code duplication can be removed easily by having a function that can return the field type for a specific mapper. 


Also I think in the KNNVectorFieldMapper this code to handle byte vectors(https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java#L549-L562) seems unnecessary.

@naveentatikonda do you remember any specific reason of having duplicated code?

**Comment by naveentatikonda** [comment]
> Also I think in the KNNVectorFieldMapper this code to handle byte vectors(https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java#L549-L562) seems unnecessary.
> 
> @naveentatikonda do you remember any specific reason of having duplicated code?

Not sure if there is any easy and better way to generalize this function because the corresponding VectorField constructor(to serialize to bytes) and other functions might also needs to be generalized.

**Comment by navneet1v** [comment]
@naveentatikonda, @jmazanec15 I created the PR for refactoring, please check. 👯‍♂️

**Comment by navneet1v** [comment]
Resolving the GH issue as the changes are merged and will be released with 2.15 version of Opensearch.
