### ISSUE TITLE
[BUG] Nightly benchmark for vectorsearch workload (faiss engine) failing with GLIBC version error

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/k-NN#1646]
**What is the bug?**
The nightly benchmarks for vectorsearch have been failing for faiss engine indices in OS-2.14.0 with below error:

```
fatal error in thread [opensearch[ip-172-31-172-58.ec2.internal][generic][T#5]], exiting
java.lang.UnsatisfiedLinkError: /home/ec2-user/opensearch/plugins/opensearch-knn/lib/libopensearchknn_faiss.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/opensearch/plugins/opensearch-knn/lib/libopensearchknn_faiss.so)
```
The same nightlies have been running fine for lucene and nmslib engine types. 
The OS process exits at `create-target-index` operation for faiss engine type. 

The OpenSearch cluster is created on `Amazon Linux 2` ec2-instances. The default GLIBC version installed on the host is `2.26`. 

**How can one reproduce the bug?**
1. Create an OS-2.14.0 cluster with k-NN plugin
2. Run vectorsearch workload benchmark using opensearch-benchmark
3. See error

**What is the expected behavior?**
There should be no failure and benchmark should complete successfully. 

**What is your host/environment?**
 - OS: Amazon Linux 2

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by jmazanec15** [comment]
Related to https://github.com/opensearch-project/opensearch-build/issues/4379#issuecomment-2045640451. cc: @peterzhuamazon 

With the change to Almalinux, AL2 will be deprecated for support because it has glibc 2.26 (https://repost.aws/questions/QUrXOioL46RcCnFGyELJWKLw/glibc-2-27-on-amazon-linux-2)

**Comment by jmazanec15** [comment]
So @rishabh6788 , post 2.14, AL2 will not be supported. Please confirm @peterzhuamazon

**Comment by jmazanec15** [comment]
Closing - this is discussed in https://github.com/opensearch-project/opensearch-build/issues/4379#issuecomment-2045640451.
