### ISSUE TITLE
CI for linux is temporarily broken

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#1668]
## Description

CI is failing for linux because we switched the base image to use opensearch-build alma linux with gcc 12. It started showing up when static linking for blas was reenabled (#1665 )

This will be fixed when we revert to gcc docker image: https://github.com/opensearch-project/opensearch-build/pull/4663.

Error will look like:
```
/opensearch-knn/lib/libopensearchknn_faiss_avx2.so: ELF load command address/offset not properly aligned [in thread "opensearch[ip-10-0-3-160.us-west-2.compute.internal][write][T#6]"]
```

**Comment by peterzhuamazon** [comment]
Waiting for: https://build.ci.opensearch.org/job/docker-build/5233/console

**Comment by peterzhuamazon** [comment]
Resolved now.
