### ISSUE TITLE
Scalability of OpenSearch-KNN

### ISSUE THREAD

**Issue by parsa-ra** [opensearch-project/k-NN#170]
We tend to employ OpenSearch-KNN for handling billion-scale vector datasets in cloud-native environment, we wonder how does OpenSearch-KNN handle scalability problem?  Is there any documentation and/or articles that deal with this matter in more detail?

**Comment by jmazanec15** [comment]
Hi @parsa-ra ,

Sorry for delay. From a high level, the k-NN plugin introduces a new File to Lucene segments that contains the data structure needed to support ANN. This file comes from nmslib. A Lucene index is made up of a set of immutable segments. A Lucene index maps to an OpenSearch shard. For scalability on a single shard, we rely on the native libraries ANN algorithms. These can scale better than a brute force search. 

We inherit cluster scalability from OpenSearch - break an index up into shards and spread them out across the cluster. If you want to scale, add nodes and make sure there is equal or more shards in the index compared to the number of nodes in the cluster. 

Heres a blog post using the plugin for [NLU](https://aws.amazon.com/blogs/machine-learning/building-an-nlu-powered-search-application-with-amazon-sagemaker-and-the-amazon-es-knn-feature/).

**Comment by parsa-ra** [comment]
Thanks for the detailed explanation @jmazanec15 

I am wondering is there any recommended approach for role of nodes when we deploy the cluster using helm-charts? Since the cluster is being deployed using Stateful sets how we can automatically scale the cluster (or we can't ?) ?

**Comment by jmazanec15** [comment]
Sorry I am not very familiar with helm. Not sure if you have seen docs [here](https://opensearch.org/docs/latest/opensearch/install/helm/). For scaling, [this article](https://docs.bitnami.com/tutorials/deploy-application-kubernetes-helm/) may be helpful.
