### ISSUE TITLE
[BWC] No Indexing and Search BWC tests added for Lucene Engine

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/k-NN#1725]
### Description
Currently in k-NN plugin there are BWC tests added for different engine and algorithms to ensure that we are able to catch any BWC issues with the new changes that happening in k-NN plugin. But for Lucene engine no BWC tests have been found.
Ref1: https://github.com/opensearch-project/k-NN/blob/main/qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java

Ref2: https://github.com/opensearch-project/k-NN/blob/main/qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java

The aim of this issue is to add the BWC tests for Lucene Engine.

**Comment by buddharajusahil** [comment]
Hi Navneet, I would like to be assigned this issue!
