### ISSUE TITLE
[BUG] CI failing on Linux with Java runtime error

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/k-NN#1737]
Linux tests are currently failing on main with a fatal Java runtime error:
```
?  #
?  # A fatal error has been detected by the Java Runtime Environment:
?  #
?  #  SIGILL (0x4) at pc=0x00007febd28ff4b9, pid=1657, tid=2008
?  #
?  # JRE version: OpenJDK Runtime Environment Zulu21.34+19-CA (21.0.3+9) (build 21.0.3+9-LTS)
?  # Java VM: OpenJDK 64-Bit Server VM Zulu21.34+19-CA (21.0.3+9-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
?  # Problematic frame:
?  # C  [libopensearchknn_faiss_avx2.so+0x4ff4b9]  sgemm_small_kernel_b0_tn+0x229
?  #
?  # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /__w/k-NN/k-NN/build/testclusters/integTest-0/distro/3.0.0-ARCHIVE/core.1657)
?  #
?  # An error report file with more information is saved as:
?  # logs/hs_err_pid1657.log
```

Example full log of failure: https://github.com/opensearch-project/k-NN/actions/runs/9455222049/job/26044511867?pr=1722

For the above PR, the tests are passing on a local Linux build.

**Comment by heemin32** [comment]
@ryanbogan Could you confirm if the failure is due the PR or not?

**Comment by ryanbogan** [comment]
@heemin32 the same error is happening on another PR here: https://github.com/opensearch-project/k-NN/actions/runs/9455190832/job/26044410766?pr=1734

**Comment by junqiu-lei** [comment]
After enabled dynamic arch for openblas build in x64 AL2 build env, the build CI is passed now, closing this issue.

More details on https://github.com/opensearch-project/opensearch-build/issues/4379

CI test example: https://github.com/opensearch-project/k-NN/actions/runs/9735975558/job/26904055122
