### ISSUE TITLE
Use index settings instead of Cluster settings to retrieve exact search threshold

### ISSUE THREAD

**Issue by kkmr** [opensearch-project/k-NN#1761]
Currently, the kNN codec uses cluster settings to retrieve the exact search threshold.  However, the same information is available in IndexSettings.  We should move away from using cluster settings and use index settings.  This lines up with the generation intention of moving away from the Cluster Setting mononlith.

**Comment by navneet1v** [comment]
@kkmr the setting is an index level setting: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/KNNSettings.java#L177-L182

I think in the docs it is mentioned as cluster level setting this could be the reason for confusion. [Ref](https://opensearch.org/docs/latest/search-plugins/knn/settings/#:~:text=The%20threshold%20value%20for%20the%20filtered%20IDs%20that%20is%20used%20to%20switch%20to%20exact%20search%20during%20filtered%20ANN%20search.%20If%20the%20number%20of%20filtered%20IDs%20in%20a%20segment%20is%20less%20than%20this%20setting%E2%80%99s%20value%2C%20exact%20search%20will%20be%20performed%20on%20the%20filtered%20IDs.)
