### ISSUE TITLE
Expose setting for tuning number of threads used for graph construction

### ISSUE THREAD

**Issue by kkmr** [opensearch-project/k-NN#1763]
In our experiments, we found that ingestion on kNN indexes was bottlenecked on graph construction.  Increasing the number of threads for this setting was helpful.  We want to be able to expose this setting so all users can tune this setting if needed.

**Comment by navneet1v** [comment]
@kkmr this setting is exposed via `knn.algo_param.index_thread_qty` [ref](https://opensearch.org/docs/latest/search-plugins/knn/settings/#:~:text=knn.algo_param.index_thread_qty). So a user can use this setting to update the number of threads used for creating the graphs.

**Comment by jmazanec15** [comment]
I think this is exposed. Going to close
