### ISSUE TITLE
[FEATURE] Support of dynamic efsearch and nprobs value during search for binary index

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/k-NN#1769]
Dynamic efsearch and nprobe is value during query time will be released in 2.16. One of its PR is https://github.com/opensearch-project/k-NN/pull/1707. 

We are also implementing binary index support to be released in 2.16. One of the PR is https://github.com/opensearch-project/k-NN/pull/1747.

Both of them is not merged in main branch yet. When they are merged, we need to make sure that binary index also support dynamic efsearch and nprobe value.

**Comment by navneet1v** [comment]
@heemin32 the code is merged for ef_search and nprobes dynamic parameters. Does binary field has picked up the support?

**Comment by heemin32** [comment]
yes for `ef_search`. 
@junqiu-lei please check if `nprobes` parameter during query time will be applied for binary ivf index.

**Comment by junqiu-lei** [comment]
> YES for `ef_search`. @junqiu-lei please check if `nprobes` parameter during query time will be applied for binary ivf index.

The `nprobes` parameter support during query time isn't available in binary format feature branch.

Will check once https://github.com/opensearch-project/k-NN/pull/1784 merge to main

**Comment by junqiu-lei** [comment]
Verified the dynamic `nprobes` is workable in query stage when use binary format IVF index:
```
http://localhost:9200/target-index/_search
{
  "size": 10,
  "query": {
    "knn": {
      "target-field": {
        "vector": [10],
        "k": 3,
        "method_parameters" : {
          "nprobes": 1
        },
        "filter": {
          "range": {
            "price": {
              "gte": 3,
              "lte": 5
            }
          }
        }
      }
    }
  }
}
```

Result:
```
{
    "took": 12,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 0.5,
        "hits": [
            {
                "_index": "target-index",
                "_id": "1",
                "_score": 0.5,
                "_source": {
                    "target-field": [
                        2
                    ],
                    "price": 4.4
                }
            }
        ]
    }
}
```
