### ISSUE TITLE
Investigate implementing the ExtensiblePlugin interface

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#180]
As discussed in https://discuss.opendistrocommunity.dev/t/how-to-build-k-nn-plugin/7482/9, currently, the k-NN plugin is not extensible. This appears to be because the plugin does not implement the [ExtensiblePlugin](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/ExtensiblePlugin.java) interface. We should investigate whether this is feasible and what would need to be done to implement it (and also confirm that implementing this plugin does make the k-NN plugin extensible).

**Comment by asfoorial** [comment]
Greetings all,

I can confirm that implementing the ExtensiblePlugin interface works very well for me. I did the below

1. I pulled the source code on my local machine and implemented the ExtensiblePlugin as shown in the code below.
2. Then I compiled the code and updated the kNN plugin with the new jar file. 
3. I created a new plugin that extend the kNN. Then I installed my new plugin.
4. My new kNN extension plugin worked well without any issues.

So I appreciate if the kNN team implement the ExtensiblePlugin in the upcoming releases.

public class KNNPlugin extends Plugin implements MapperPlugin, SearchPlugin, ActionPlugin, EnginePlugin, ScriptPlugin, ExtensiblePlugin
{
…
}

**Comment by martin-gaievski** [comment]
> Greetings all,
> 
> I can confirm that implementing the ExtensiblePlugin interface works very well for me. I did the below
> 
> 1. I pulled the source code on my local machine and implemented the ExtensiblePlugin as shown in the code below.
> 2. Then I compiled the code and updated the kNN plugin with the new jar file.
> 3. I created a new plugin that extend the kNN. Then I installed my new plugin.
> 4. My new kNN extension plugin worked well without any issues.
> 
> So I appreciate if the kNN team implement the ExtensiblePlugin in the upcoming releases.
> 
> public class KNNPlugin extends Plugin implements MapperPlugin, SearchPlugin, ActionPlugin, EnginePlugin, ScriptPlugin, ExtensiblePlugin { … }

Hello @asfoorial

Thank you for testing the approach with the ExtensiblePlugin interface. 

You can actually achieve the same result without waiting for the changes from kNN team. You should be able to extend the KNNPlugin class and implement the ExtensiblePlugin directly in your class, something like the code below:

public class MyPlugin extends KNNPlugin implements ExtensiblePlugin {

    @Override
    public void loadExtensions(ExtensionLoader loader) {
         .......
    }
}

as the kNN team still working on identifying potential extension points this can be a good solution that allows you to move forward faster and flexibility of implementing your own extension points.
