### ISSUE TITLE
[RFC] Design to Store Quantization State 

### ISSUE THREAD

**Issue by Vikasht34** [opensearch-project/k-NN#1890]
# Design Strategy for Quantization State Persistence
## Introduction
This document outlines the design for storing the quantization state. It includes essential information on the thresholds required for quantizing a vector
## Problem Statement

In the process of quantization during indexing, it is essential to store the quantization state generated during training. This quantization state contains critical threshold information required for accurate vector quantization. During search time, the query vector must be quantized using the same thresholds and parameters established during training to maintain consistency and accuracy. The objective is to design a robust system for storing and retrieving the quantization state to facilitate precise and efficient quantization of query vectors during search operations and Indexing.
![Untitled Diagram-Page-14 (1) (1)](https://github.com/user-attachments/assets/ed99caff-0bfe-47b2-b071-44876b596138)
### Functional
* Support ability to store the quantization state at segment level in a persistent storage .
* The storage mechanism shall support efficient read and write operations for the quantization state.
* The storage mechanism shall ensure that the quantization state is easily retrievable during search operations at segment level
### Non-Functional Requirements
Performance:

* The system shall retrieve the quantization state with  to ensure fast query processing.

Scalability:

* The storage mechanism shall be scalable to handle a large number of quantization states and corresponding data.

Reliability:

* The system shall ensure the integrity and consistency of the stored quantization state.

Usability:

* The interfaces for storing and retrieving the quantization state shall be intuitive and easy to use.

## High Level Design
During the indexing flow, where raw data is processed through a training phase within the quantization framework to generate a quantization state.This state is then saved per segment in the HNSW index files, alongside other data structures such as the header, graph, raw vectors, and a footer containing a checksum for data integrity verification.
Each segment file (S1, S2, ..., Sn) contains the quantization state, ensuring that the system maintains comprehensive and segment-specific quantization information. During the search flow, the system reads the quantization state from each segment file. This state is then passed to the quantization framework, which utilizes it to quantize the vectors as required for the search operations.
To enhance performance, the quantization states to be cached.

### Architecture
![Untitled Diagram-Page-15 (2) (1)](https://github.com/user-attachments/assets/a0e52414-85fd-40d0-b5e0-5ddf1951db0f)

#### Why to write to new file 
Pros:- 
* Should be  able to re-use Lucene abstractions on file handling for better I/O
* Quantization State is not tightly coupled with engine file , so it removes restrictions on saving independently.

Cons:- 
* Simplifies the file management process as you have fewer files to handle.
* Keeps all related data in a single file, which can be easier for certain backup and restore strategies.
* Each file in a filesystem is associated with an inode, which stores metadata about the file such as its size, owner, permissions, and pointers to data blocks.
* By writing to an existing file, the same inode is reused, avoiding the overhead of creating a new inode.
* Since no new file is created, there is less metadata to update in the filesystem, such as directory entries and inode tables. This can lead to marginally faster operations, especially in scenarios with high file creation and deletion rates.

### Component Diagram 
![Untitled Diagram-Page-16 (4)](https://github.com/user-attachments/assets/5f4d3b1e-6ca7-4ba6-b090-f509219bbdd0)
The indexing flow begins with the ingestion of documents into the NativeEnginesKNNVectorsWriter, where vectors are processed and then passed to the NativeIndexTrainingManager along with the VectorValueIterator, FieldInfo, and SegmentState. The NativeIndexTrainingManager creates a training request and communicates with the Quantization Framework to train the quantizer. Once trained, the Quantization Framework returns the QuantizationState to the TrainingManager. The TrainingManager then passes the QuantizationState along with other data to the NativeIndexCreationManager, which is responsible for writing quantization state to new file and it will be cached to avoid disk seeks.
### Effectively Read and Write Quantization State to Index File
![image (5)](https://github.com/user-attachments/assets/fa0cad66-7425-4a94-b927-7709873185d2)
The diagram outlines the process for writing and reading QuantizationState using Lucene's IndexOutput and IndexInput abstractions. First, the client opens an IndexOutput stream via Lucene's Directory interface, which standardizes file operations within the Lucene ecosystem. This stream is used to serialize and write the QuantizationState data efficiently.
After writing the data, the IndexOutput is closed to ensure that all buffered data is flushed to disk and the file is properly closed. For reading, an IndexInput stream is opened, again via the Directory interface, to deserialize and reconstruct the QuantizationState. This approach not only ensures data integrity but also optimizes I/O operations by leveraging Lucene's built-in file handling mechanisms, which are designed for high-performance and scalability. Using these abstractions, developers can seamlessly integrate quantization state management into Lucene-based systems without deviating from standard practices.

**Comment by navneet1v** [comment]
@Vikasht34 can you please add more details on how the QS will be accessed in the KNNWeightClass? I didn't find much details on after reading the issue.
