### ISSUE TITLE
[BUG] KNN vector. error when inserting new vector after ~10 million docs in index

### ISSUE THREAD

**Issue by harelfar2** [opensearch-project/k-NN#1891]
### Describe the bug

I'm using AWS hosted OpenSearch
1 instance cluster machine:  r5.2xlarge.search

I have a knn index with this mapping: 
```
{
    "settings": {
        "index.knn": True,
        "index.knn.space_type": "l2",
    },
    "mappings": {
        "properties": {
            "embeddings": {
                "type": "knn_vector",
                "dimension": 768,
                "method": {
                    "name": "hnsw",
                    "space_type": "l2",
                    "engine": "nmslib",
                    "parameters": {
                        "ef_construction": 50,
                        "m": 4
                    }
                },
                "store": False,
            },
            "case_id": {
                "type": "keyword",
                "store": True,
            },
        }
    },
}
```
I inserted ~10 million vectors to it, played with some searches, and inserted and removed some vectors.
Suddenly, the searches [appx-knn, exact-knn] became very slow (didn't fail). 
Then when I tried to insert a vector like this:
```
        body = {
            "embeddings": vector,
            "case_id": case_id,
        }
        self.client.index(
            index=self.index_name,
            body=body,
            id=doc_id,
            refresh=True,
        )
```
I get this error: 
`opensearchpy.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [embeddings] of type [knn_vector] in document with id 'dolls'. Preview of field's value: '[0.29271504282951355, 0.19183756411075592 ...]`

I'm certain that my vector's dimensions are correct, and the exact same insertion code worked before for sure.
I've also created a new index with same mapping, and I cannot insert there either, so there's something probably messed up with the cluster. 

It's not the first time that I'm experiencing it. It happened to me when I created and played with a previous cluster. 

Thanks ahead for your help.

### Related component

Other

### To Reproduce

1. create a knn_vector mapping
2. insert 1 million documents.
3. refresh index and wait for it to finish.
4. make some apprx-knn remove some docs.
5. try to add new document
6. get the failure message.

### Expected behavior

I'm expecting the insertion to succeed

### Additional Details

**Plugins**
KNN-vector 

**Host/Environment (please complete the following information):**
 - OS: AWS hosted. machine: r5.2xlarge.search
 - Version OpenSearch 2.13 (latest)
 - Service software version: OpenSearch_2_13_R20240520-P4 (latest)

**Comment by jmazanec15** [comment]
@harelfar2 Can you run `GET _plugins/_knn/stats?pretty`? I suspect circuit breaker is tripped. Also, is there more to the error message or just that?

**Comment by harelfar2** [comment]
Hi @jmazanec15.
sure: 
```
{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "983918838720:harel-2",
  "circuit_breaker_triggered": true,
  "model_index_status": null,
  "nodes": {
    "RBkrgPUKSmSRhePD8x24-A": {
      "graph_memory_usage_percentage": 94.09987,
      "graph_query_requests": 3828,
      "graph_memory_usage": 15546175,
      "cache_capacity_reached": true,
      "load_success_count": 858,
      "training_memory_usage": 0,
      "indices_in_cache": {
        "smaller-ef": {
          "graph_memory_usage_percentage": 94.09987,
          "graph_memory_usage": 15546175,
          "graph_count": 135
        }
      },
      "script_query_errors": 0,
      "hit_count": 1550,
      "knn_query_requests": 42,
      "total_load_time": 2444605697931,
      "miss_count": 944,
      "knn_query_with_filter_requests": 0,
      "training_memory_usage_percentage": 0,
      "lucene_initialized": false,
      "graph_index_requests": 1056,
      "faiss_initialized": false,
      "load_exception_count": 0,
      "training_errors": 0,
      "eviction_count": 636,
      "nmslib_initialized": true,
      "script_compilations": 1,
      "script_query_requests": 310,
      "graph_stats": {
        "merge": {
          "current": 0,
          "total": 94,
          "total_time_in_millis": 5974555,
          "current_docs": 0,
          "total_docs": 16582756,
          "total_size_in_bytes": 51008557656,
          "current_size_in_bytes": 0
        },
        "refresh": {
          "total": 962,
          "total_time_in_millis": 3201927
        }
      },
      "graph_query_errors": 0,
      "indexing_from_model_degraded": false,
      "graph_index_errors": 0,
      "training_requests": 0,
      "script_compilation_errors": 0
    }
  }
}
```

And there is no further to the error I gave (except for python stack trace)

**Comment by harelfar2** [comment]
look like you are right and it's a circuit breaker issue. 
I raised knn.memory.circuit_breaker.limit to 99% and it released the CB. 
However, I this there is a bug here, that the graph memory is not being released.

**Comment by heemin32** [comment]
Graph memory is released in three condition.
1. Delete the index
2. Call clear the cache knn API https://opensearch.org/docs/1.0/search-plugins/knn/api/
3. When you load new graph index(either by calling knn load API or by calling search API on knn index), it automatically release least used index.

However, the third condition does not work during indexing where we use off heap memory temporary.

**Comment by harelfar2** [comment]
Tanks @heemin32 
Isn't there a 4th condition of index being idle? 
Is it this property: `knn.cache.item.expiry.enabled`?
If I'm correct, I see that the default value of it is false, shouldn't it be true (defaults are important :) )?
Anyways, I think there must be some mechanism so one graph should not allocate so much memory, so we would reach this state.

Thanks.

**Comment by heemin32** [comment]
You are right. You can set `knn.cache.item.expiry.enabled` along with `knn.cache.item.expiry.minutes`.
The reason that the value is false as default is to avoid increased latency on query request hitting the expired index in production environment. There is no right or wrong in the default setting I think. You can set the value as you wish. 
The memory consumption is based on your vector data size. See https://opensearch.org/docs/latest/search-plugins/knn/knn-index/#hnsw-memory-estimation

Ideally, you may want to use machine with more memory or you can consider quantization of your vector data. https://opensearch.org/docs/latest/search-plugins/knn/knn-vector-quantization/

**Comment by harelfar2** [comment]
Yah, I get that.. 
The thing is that I just inserted some amount of vectors, made a search, and without any warning, the whole cluster went numb. 

I'd would expect some indication, perhaps in insertion time. At the very list, a proper exception indicating memory problem, and not that my filed is incorrect.

**Comment by heemin32** [comment]
Since version 2.15 it will have user friendly exception message. https://github.com/opensearch-project/k-NN/pull/1688

**Comment by harelfar2** [comment]
great!
thanks a lot for all your help
