### ISSUE TITLE
[BUG] KNNQueryBuilder sets ```k```and ```minScore``` together

### ISSUE THREAD

**Issue by safakkbilici** [opensearch-project/k-NN#1903]
**Describe the bug**
I am integrating ```KNNQueryBuilder``` into my application to ensure k-NN queries are compatible with other query builders within the OpenSearch Java client. In the DSL, I typically utilize the ```minScore``` parameter, without specifying ```k``` or ```maxDistance```. However, within ```KNNQueryBuilder```, despite not explicitly setting the ```k``` parameter, it defaults to ```"k": 0```. This results in an error at the client level:

```
"caused_by": {
   "type": "illegal_argument_exception",
   "reason": "[knn] requires exactly one of k, distance or score to be set"
}
```

The query builder looks like this:

```java
KNNQueryBuilder knnQueryBuilder = new KNNQueryBuilder("name_vector", searchQuery.getEmbedding()).minScore(0.001f).boost(1);
```

and I use the default search method

```java
this.client.search(searchRequest, RequestOptions.DEFAULT);
```

**To Reproduce**
- Set minScore but not k parameter
- Search it

**What is the expected behavior?**
I'm expecting if `the parameter ```k``` does not given at all (or set to be null), do not include it.

**What is your host/environment?**
 - Version OpenSearch 2.14

**What could be a solution?**
If the parameter ```k``` is passed as ```null```, then do not write in ```doWriteTo``` method.

**Comment by heemin32** [comment]
@safakkbilici Thanks for reporting the issue. We were aware of it but didn't thought there is a user using the KNNQueryBuilder directly from their application. 
An alternative would be adding K-NN support in OpenSearch Java client.

**Comment by jmazanec15** [comment]
@vamshin to triage

**Comment by jmazanec15** [comment]
Lets close - recommendation is to use OpenSearch java client
