### ISSUE TITLE
Update copyright notices and license headers

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/k-NN#193]
Update: the correct copyright is Copyright OpenSearch Contributors, without All Rights Reserved, without years for the OpenSearch part (leave years if any Elastic copyright is needed), and no Amazon-related stuff.

- [x] Do you have a Copyright OpenSearch Contributors in README?
- [x] Does copyright Copyright OpenSearch Contributors match between NOTICE.txt or NOTICE and README?
- [x] Did you remove the year from Copyright 2021 OpenSearch Contributors in README and NOTICE?
- [x] Do you have other copyrights properly represented in NOTICE, such as Elastic, if your code was forked?
- [x] Did you remove all Copyright Amazon and Affiliates?
- [x]  Did you remove any other .md files that say anything about copyright?
- [x] Is your CONTRIBUTING.md up-to-date saying to use short versions?
- [x]  Are you using short versions in your files? See Update OpenSearch LicenseHeaders to use the short version

**Comment by AMoo-Miki** [comment]
The correct header for files like [this one](https://github.com/opensearch-project/k-NN/blob/main/build.gradle) is:

```
/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
```

For files that contain attribution to an external project, place this long version above those of the external project(s).

```
/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */
```

Here is a rough list of files that need to change: 
https://github.com/opensearch-project/k-NN/search?q=copyright+amazon.com+reserved

**Comment by naveentatikonda** [comment]
> The correct header for files like [this one](https://github.com/opensearch-project/k-NN/blob/main/build.gradle) is:
> 
> ```
> /*
>  * Copyright OpenSearch Contributors
>  * SPDX-License-Identifier: Apache-2.0
>  */
> ```
> 
> For files that contain attribution to an external project, place this long version above those of the external project(s).
> 
> ```
> /*
>  * Copyright OpenSearch Contributors
>  * SPDX-License-Identifier: Apache-2.0
>  *
>  * The OpenSearch Contributors require contributions made to
>  * this file be licensed under the Apache-2.0 license or a
>  * compatible open source license.
>  *
>  * Modifications Copyright OpenSearch Contributors. See
>  * GitHub history for details.
>  */
> ```
> 
> Here is a rough list of files that need to change: https://github.com/opensearch-project/k-NN/search?q=copyright+amazon.com+reserved

Thank you, will update it.

**Comment by VijayanB** [comment]
Lets close this once all files are updated!
