### ISSUE TITLE
[BUG] Vector search with HNSW with Lucene engine does not return default (3) results in the nested knn_vector

### ISSUE THREAD

**Issue by saifkhan-m** [opensearch-project/k-NN#1937]
### What is the bug?

The vector search in nested vector fields should return appropriate (default=3 or equal to `size` parameter) results.

I want to create an index where I could do [Efficient k-NN filtering](https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/).
I have created 2 indices:
1. HNSW with `nmslib` engine and `cosinesimil` space
2. HNSW with `Lucene` engine and `cosinesimil `space

I want to search similar vectors in the nested fields. When I query the 1st index the hits contains the documents that match the vector and return the document with 3 `inner_hits`vectors. But when I query the 2nd index, only 1 `inner_hits` vector is returned. And I am not even applying any filters in the query yet.

### How can one reproduce the bug?
1. Mapping for index 1
```
{
  "properties": {
    "chunks": {
      "type": "nested",
      "properties": {
        "chunk_id": {
          "type": "keyword"
        },
        "content": {
          "type": "text"
        },
        "title": {
          "type": "text"
        },
        "vector_embedding": {
          "dimension": 1536,
          "method": {
            "engine": "nmslib",
            "space_type": "cosinesimil",
            "name": "hnsw",
            "parameters": {}
          },
          "type": "knn_vector"
        }
      }
    },
    "doc_meta2": {
      "type": "keyword"
    },
    "document_id": {
      "type": "keyword"
    },
    "document_name": {
      "type": "keyword"
    }
  }
}
```
Query for index 1:
```
POST docs_nested_embedding_kw/_search
{
  "_source": false,
  "query": {
    "nested": {
      "path": "chunks",
      "query": {
        "knn": {
          "chunks.vector_embedding": {
            "vector": [ <vector_query>]
            ],
            "k": 5
          }
        }
      },
     "inner_hits": {
        "_source": false,
        "fields": [
          "chunks.content"
        ],
        "size": 5
      }
    }
  }
}
```
2. Mapping for index 2
```
{
  "properties": {
    "chunks": {
      "type": "nested",
      "properties": {
        "chunk_id": {
          "type": "keyword"
        },
        "content": {
          "type": "text"
        },
        "title": {
          "type": "text"
        },
        "vector_embedding": {
          "dimension": 1536,
          "method": {
            "engine": "lucene",
            "space_type": "cosinesimil",
            "name": "hnsw",
            "parameters": {}
          },
          "type": "knn_vector"
        }
      }
    },
    "doc_meta2": {
      "type": "keyword"
    },
    "document_id": {
      "type": "keyword"
    },
    "document_name": {
      "type": "keyword"
    }
  }
}
```
Search query for index 2:
```
POST docs_nested_embedding_kw_filter/_search
{
  "_source": false,
  "query": {
    "nested": {
      "path": "chunks",
      "query": {
        "knn": {
          "chunks.vector_embedding": {
            "vector": [  <vector_query> ],
            "k": 5
          }
        }
      },
      "inner_hits": {
        "_source": false,
        "fields": [
          "chunks.content"
        ],
        "size": 5
      }
    }
  }
}
```

### What is the expected behavior?
Both the index should return at least the default inner hits. Only the the query in index 1 is returning the default hits. 
If the size parameter is present in the `inner_hits` query, then total inner hits equal to the size should be returned. Again this is only happening with index 1 and not with index 2.

### What is your host/environment?
Windows 10 Pro
Opensearch version: I am using docker image `opensearchproject/opensearch:latest` 
```
{
  "name" : "opensearch-node1",
  "cluster_name" : "opensearch-cluster",
  "cluster_uuid" : "VmHwfgBeS6q2GQ03tqQWlw",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.15.0",
    "build_type" : "tar",
    "build_hash" : "61dbcd0795c9bfe9b81e5762175414bc38bbcadf",
    "build_date" : "2024-06-20T03:26:49.193630411Z",
    "build_snapshot" : false,
    "lucene_version" : "9.10.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

### Do you have any screenshots?
The request and results from **first index**.
![image](https://github.com/user-attachments/assets/ba88418b-322c-492d-8e41-4a1582e88c67)

![image](https://github.com/user-attachments/assets/de7fb8b6-513f-42e8-9878-4f55f688a0cc)

The  request and results from **second index**.
![image](https://github.com/user-attachments/assets/e825b9c8-ae57-4316-9079-470f5099008a)

![image](https://github.com/user-attachments/assets/c98befb4-ffc5-45b9-940e-ba67fe8a7395)

### Do you have any additional context?
1. I also played with different values of `k` setting it to 10 and 20 but still one `inner_hits` is returned.
2. I created an index using HNSW with `faiss` engine and `l2` space. I am still only getting 1 results in the `inner_hits`.
![image](https://github.com/user-attachments/assets/a6c5e105-1d3e-4656-bb9a-64b8000e32d0)

**Comment by martin-gaievski** [comment]
transferring to k-NN because it's related to kNN query
