### ISSUE TITLE
Update integTest gradle scripts to run via remote cluster independently

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/k-NN#198]
**Is your feature request related to a problem?**
With the existing implementation of integration tests, opensearch plugins use the same test framework as local integration tests which spin up test clusters by itself. This is a hacky way to override the endpoint from local spun up test clusters (via `opensearch.testclusters` gradle plugin) with the remote cluster endpoint. 

The solution doesn't work when we would like to test the opensearch bundle as part of the release. The test frameworks expect the artifact to be available before we could test them. To clean this up, plugins have to create gradle scripts for remote endpoints to run https://github.com/opensearch-project/opensearch-build#integration-tests for the release cycle. 

**What solution would you like?**
Refer to: https://github.com/opensearch-project/anomaly-detection/pull/298 and make similar changes to the plugin.
Also if you have a custom name to invoke these tests, update the `integtest.sh` script in https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh

**Comment by jmazanec15** [comment]
Hi @saratvemulapalli what release is this issue targetted for?

**Comment by saratvemulapalli** [comment]
@jmazanec15 this is intended for 1.2 if K-NN would like to onboard to automated release integration tests.

**Comment by martin-gaievski** [comment]
Required changes were made to 1.3
