### ISSUE TITLE
[BUG]The `MIN_OVERSAMPLE_FACTOR` is set to `0`.

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/k-NN#2112]
**What is the bug?**
The `MIN_OVERSAMPLE_FACTOR` is [currently set as 0](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java#L21) in RescoreContext. If I understand correctly, it should be set to 1. I think setting it to 0 makes it have no effect on [this formula](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java#L46).

**Comment by kkhatua** [comment]
@jmazanec15 ... why didn't the UTs catch this?

**Comment by jmazanec15** [comment]
@kkhatua its a ux bug not a functional bug.

**Comment by jmazanec15** [comment]
more about experience than breaking
