### ISSUE TITLE
[Maintenance] Back-port branches not getting deleted

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/k-NN#2128]
### Issue
Whenever a PR needs to be backported to 2.x branch we add a label : `backport-2.x` to that PR. Due to this its creates a backport branch like `backport/backport-2058-to-2.17`. There is a GH action: https://github.com/opensearch-project/k-NN/blob/main/.github/workflows/delete_backport_branch.yml which was supposed to delete this branch, but that GH action is failing(https://github.com/opensearch-project/k-NN/actions/workflows/delete_backport_branch.yml) and hence branches are not getting deleted. This issue tracks the fix for that GH action.

Fix: https://github.com/opensearch-project/OpenSearch/commit/3a1b6d1795f23f2d14c4f2174867ce70ed88525e

**Comment by 0ctopus13prime** [comment]
Will work on this.
