### ISSUE TITLE
[FEATURE] Evict graphs from cache when index is closed or delete for indices that are created using NativeEngines990KnnVectorsFormat

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/k-NN#2148]
**Is your feature request related to a problem?**
This PR #1946 clears graph from cache whenever index is closed or deleted to save memory. However this works only for indices created using BinaryDocValues. With 2.17. k-NN uses NativeEngines990KnnVectorsFormat, hence, we need similar feature for indices that are created using this new format.

**What solution would you like?**
Evict graph when index is closed or deleted irrespective of vector format.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
N/A

**Comment by navneet1v** [comment]
@0ctopus13prime do you want to pick this task up as part of removing the file watcher dependency from k-NN plugin?

**Comment by 0ctopus13prime** [comment]
@navneet1v 
Hi Navneet! Sorry, I just saw your comment.
And as you know, the related PR was merged for both main and 2.x, I think we can close this out!

**Comment by navneet1v** [comment]
Closing out this issue after getting confirmation from @0ctopus13prime
