### ISSUE TITLE
Switch default vector engine from nmslib to faiss

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/k-NN#2163]
**Is your feature request related to a problem?**
The nmslib vector engine is currently in maintenance mode as of 10/27, and we plan to deprecate it in the 3.x version. All the feature development/optimizations are focused in faiss engine since 2.7 version. To align the new vector indexes with these improvements, it would be beneficial to switch the default vector engine from nmslib to faiss.

**What solution would you like?**
Switch the default vector engine from nmslib to faiss.

**Comment by navneet1v** [comment]
@vamshin I see this issue is put in 2.18 version? is the feature planned for 2.18?

**Comment by vamshin** [comment]
@navneet1v yes, idea is to do for 2.18

**Comment by vamshin** [comment]
As part of this default switch to faiss, I feel we should also switch to fp_16 with in faiss.

**Comment by jmazanec15** [comment]
I think that until we can automatically handle cases where the data may not fit inside fp_16, we should not do this yet. Instead, for OOTB experience, users can specify compression and/or mode. If needed, we can introduce a new mode or similar meta parameter.

**Comment by vamshin** [comment]
For 2.18, we can just make faiss default and later figure out plan for making fp_16 as default.

**Comment by navneet1v** [comment]
closing this issue as 2.18 is released.

**Comment by dblock** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/andrross/), [4](https://github.com/dolla24)]
