### ISSUE TITLE
[BUG] Cannot Install k-NN plugin via Homebrew

### ISSUE THREAD

**Issue by Petercopter** [opensearch-project/k-NN#2197]
### Describe the bug

I've installed OpenSearch via Homebrew on MacOS (M1). I'm trying to install the k-NN search plugin, but I'm getting an error.

### Related component

Build

### To Reproduce

```
brew install opensearch
```
then
```
opensearch-plugin install opensearch-knn
```
returns
```
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
-> Installing opensearch-knn
-> Failed installing opensearch-knn
-> Rolling back opensearch-knn
-> Rolled back opensearch-knn
A tool for managing installed opensearch plugins

Non-option arguments:
[String] -- command  

Option             Description        
------             -----------        
-E <KeyValuePair>  Configure a setting
-h, --help         Show help          
-s, --silent       Show minimal output
-v, --verbose      Show verbose output
ERROR: Unknown plugin opensearch-knn
```

### Expected behavior

Plugin should install

### Additional Details

My coworker was able to install a different plugin as a test using
```
opensearch-plugin install query-insights
```
So this could be specific to the opensearch-knn plugin.

**Plugins**
Please list all plugins currently enabled.

**Host/Environment (please complete the following information):**
 - OS: MacOS (M1)
 - Version Sequoia 15.0

**Comment by jmazanec15** [comment]
@opensearch-project/admin I didnt realize installing from opensearch-plugin was supported for distro plugins. Could this be moved to opensearch-build repo for onboarding k-NN?

**Comment by peterzhuamazon** [comment]
Homebrew currently only have core I believe and it is barebone.
We didnt officially announce any macOS bundle yet.
Only a barebone core in core repo on homebrew, and snapshot core tar artifact with direct download.

Thanks.

**Comment by peterzhuamazon** [comment]
Plus, we do not support knn on macOS yet.

**Comment by gaiksaya** [comment]
Hi @Petercopter ,

We do not support macos distribution yet. See the supported distributions on the download page https://opensearch.org/downloads.html
We do have issues open for [macos](https://github.com/opensearch-project/opensearch-build/issues/38) and [homebrew support](https://github.com/opensearch-project/opensearch-build/issues/1589) for future enhancements.

**Comment by navneet1v** [comment]
Closing this issue as there are already GH issues created to support the mac os distribution
