### ISSUE TITLE
Default CI Java Version to Java 11, run tests on 8, 14 and 17

### ISSUE THREAD

**Issue by dblock** [opensearch-project/k-NN#220]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/64, default CI Java version to 11 (LTS), and run tests on 8, 14 and 17.

- [x] Change the default Java version for CI in GitHub actions from 14/15 to 11 (LTS).
- [ ] Add Java 8, 14 (used before), and 17 (next LTS) to the CI matrix.
- [x] Document Java versions in DEVELOPER_GUIDE.md.

**Comment by martin-gaievski** [comment]
Added JDK 11 and set it as a default version in DEVELOPER_GUIDE.md.

For JDK 8 and JDK 17 there are some issues and we don't solution yet. For JDK 8 it's OS, seems it has been compiled with JDK 9:

org/opensearch/gradle/plugin/PluginPropertiesExtension has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
https://github.com/martin-gaievski/k-NN/runs/4945583353?check_suite_focus=true

for JDK 17 higher gradle version is required, I've tested with 7.3.3. It fails with

Error: Exception in thread "main" java.lang.NoClassDefFoundError: org/gradle/cli/CommandLineParser
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:43)
https://github.com/opensearch-project/k-NN/runs/4957612326?check_suite_focus=true
I've tried multiple things locally - different gradle versions, generating new gradle wrapper, setting java language level for tooling etc., but no success.

**Comment by martin-gaievski** [comment]
There is a related issue for OpenSearch in relation to JDK 8 and 17 [Remove support for Java 8, add support for Java 17](https://github.com/opensearch-project/opensearch-plugins/issues/110). KNN is blocked until that issue is addressed by the OpenSearch team.

**Comment by martin-gaievski** [comment]
Merged [#2025](https://github.com/opensearch-project/OpenSearch/pull/2025) to address JDK 8 and JDK 17 requirements. Change is for OpenSearch 2.0 release, and not going to be ported to 1.x. As k-NN follows OpenSearch release path/versions, this means build issues for k-NN 1.x still remain unresolved. Suggesting to close this issue or move it to 2.0 release.

**Comment by dblock** [comment]
@martin-gaievski Care to pitch in a comment for https://github.com/opensearch-project/opensearch-plugins/issues/110#issuecomment-1032811256 pls?

**Comment by reta** [comment]
@martin-gaievski for 2.0.0, the upgrade to Gradle 7.x is required, I could submit the PR for `k-NN`, wdyt?

**Comment by martin-gaievski** [comment]
> 

@reta sure Andriy, we haven't released knn 1.3 yet, so current main is gonna be used for this. Let me discuss with the team if we can cut off 1.3 release branch soon, if so I'll put an update here and you can continue with PR.

**Comment by reta** [comment]
Thanks @martin-gaievski ! Sure, please take you time!

**Comment by martin-gaievski** [comment]
@[reta](https://github.com/reta) please go ahead with the PR. For knn we have created branch [1.x](https://github.com/opensearch-project/k-NN/tree/1.x) that will serve for any 1.x releases, so main is good to go for 2.x changes.

**Comment by martin-gaievski** [comment]
Solve all issues related to 1.3 knn release, closing this one
