### ISSUE TITLE
Allow method parameter override for training based indices

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#2246]
## Description

From mode/disk-based feature, we introduced concept of mode and compression level that will dynamically set default resolution. For indices created directly from the method (i.e. mapping) we allow users to override parameters if they want.

However, for training, we added the mode and compression, but made them mutually exclusive with method. See: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java#L138-L139. We need to remove this and allow method overriding to provide a consistent ux experience across the plugin.

**Comment by buddharajusahil** [comment]
Hey Jack! Could you please assign me to this issue?
