### ISSUE TITLE
[BUG] GPL 2.0 License

### ISSUE THREAD

**Issue by perleino** [opensearch-project/k-NN#2291]
**What is the bug?**
As i understand Opensearch is under Apache 2.0 license. How ever it looks like K-NN is using https://github.com/opensearch-project/k-NN/blob/main/micro-benchmarks/build.gradle#L30  jmh-core that is under GPL 2.0 license: https://github.com/openjdk/jmh/blob/master/LICENSE is this OK from a license perspective ? Should the https://github.com/opensearch-project/k-NN/blob/main/micro-benchmarks be marked as GPL 2.0 ?

**How can one reproduce the bug?**
N/A

**What is the expected behavior?**
N/A

**What is your host/environment?**
N/A

**Do you have any screenshots?**
N/A

**Do you have any additional context?**

**Comment by navneet1v** [comment]
@perleino this could have been added by mistake. This package was inspired from: https://github.com/opensearch-project/OpenSearch/blob/main/benchmarks/build.gradle#L54 If jmh is not Apache license, we can remove this module.

**Comment by dblock** [comment]
@navneet1v @vamshin Can someone pick this one up please ASAP?

[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/andrross/), [3](https://github.com/reta)]

**Comment by navneet1v** [comment]
Will raise a PR today to remove the module. and later I will see how we can fix it. I see Lucene is also using the same. Let me see how they have implemented this and get away from this GPL thing.
Ref: https://github.com/apache/lucene/tree/main/lucene/benchmark-jmh

**Comment by navneet1v** [comment]
Resolving the GH issue. Since the module is removed.
