### ISSUE TITLE
[BUG] Integ test and futuer BWC test will be running only with exact search

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/k-NN#2329]
After introducing this setting where we don't build a graph when the number of document per segment is less than [15,000](https://github.com/opensearch-project/k-NN/blob/2b9a741a7cfb8c9a55c7412a6e19ea699b7a921d/src/main/java/org/opensearch/knn/index/KNNSettings.java#L101), all existing integ test and bwc test after 2.19 might be running only in exact search mode but not approximate search mode.

We will fail to catch issue related with ANN search through the integ and bwc test.

**Comment by VijayanB** [comment]
Not all tests are running using Exact search, new method was created to pass threshold as 0 to build graph always. Some of the tests were updated with this new method. However, will create PR to force all test to run Approximate Search as default.
