### ISSUE TITLE
Flaky test cases causing CI to fail in 1.2

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#245]
Test cases in src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java are causing CI for 1.2 to fail. These should be fixed. 

Related failures:
1. https://github.com/opensearch-project/k-NN/pull/243

**Comment by navneet1v** [comment]
Resolving the issue as we are not facing this issue now.
