### ISSUE TITLE
[BUG] Upgrade from 1.0,1.1 to 1.2,1.3 fails when parameters set to null

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#353]
**What is the bug?**
When a user in 1.0 or 1.1 creates an index with parameters set to null or not set, the default parameters are used. However, in 1.2/1.3, when null parameters are being read in KNNMethodContext, it throws an exception when parsing null values. This can cause issues when upgrading from 1.0, 1.1 to 1.2, 1.3.

Code refs:
OS 1.2 --> https://github.com/opensearch-project/k-NN/blob/1.2/src/main/java/org/opensearch/knn/index/KNNMethodContext.java#L194
OS 1.1 --> https://github.com/opensearch-project/k-NN/blob/1.1/src/main/java/org/opensearch/knn/index/KNNMethodContext.java#L151

**How can one reproduce the bug?**
1. Create k-NN index on OpenSearch 1.1 domain with parameters = null (or not set) in mapping
```
POST /myindex
{
  "my_vector": {
    "type": "knn_vector",
    "dimension": 4,
    "method": {
      "name": "hnsw",
      "space_type": "l2",
      "engine": "nmslib"
    }
  }
}
```
2. Upgrade domain to 1.2/1.3 - mapping will be unable to be parsed on upgrade

**Mitigations**
One potential mitigation would be to reindex the index into an index on 1.1 before upgrading that contains the parameters set for the mapping. 

Otherwise, a code change will be required.

**What is the expected behavior?**
Null input should be valid and not cause failure on upgrade.

**Comment by dblock** [comment]
Needs a test case that covers this scenario in bcw tests as well, please.

**Comment by jmazanec15** [comment]
@dblock Will add additional BWC test for this as well as other cases - going to brainstorm cases and put them in a new issue. Refactoring BWC test structure in #359 to isolate BWC tests from other integ tests.
