### ISSUE TITLE
[FEATURE] Lucene Based k-NN search support

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/k-NN#380]
**Is your feature request related to a problem?**
Recently Lucene started building in-house Approximate k-NN search in Java based on HNSW algorithm. k-NN plugin already has support for HNSW based out of C library namely NMSlib. By having the Lucene based HNSW support, we will be able to provide AKNN functionality independently outside of k-NN plugin with out having to rely on the NMSlib or FAISS. This will unlock the platform dependency issues because of C based libraries.

As a prerequisite we need to introduce new data type [dense_vector](https://github.com/opensearch-project/k-NN/issues/39) in OpenSearch core and build Field Mappers to index data from this field to Lucene graphs.

**Comment by elfisher** [comment]
I added the roadmap label since this is on the project roadmap.

**Comment by alexahorgan** [comment]
Demo feedback (8/3/22):

**Outcome:**
Approved, ship it. 

**Action Items/Follow up:**
-  Connect with documentation team to document limits and approaches. 
-  Follow up on performance and scale. 
-  Begin exploring opportunities to leverage UI to drive insights/run searches.
