### ISSUE TITLE
Add support for auto-generation of Java boilerplate code 

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/k-NN#390]
Plugin is missing support of some sort of a code generator library that simplifies/automates creation of a boilerplate Java code. This should save engineers time, and increase code unification, maintainability and readability at the same time.

**Comment by jmazanec15** [comment]
@martin-gaievski this seems like something that would clean up the code significantly.

I have a couple questions: 
1. For auto-generated methods, what is the best practice for unit testing?
2. Can you provide a few candidate classes that we could convert to use lombok? I do have too much familiarity with lombok and would like to try it out.
3. What are the associated risks with adding automated boilerplate creation? I have read a few articles where there are a few risks. How do we mitigate them?
