### ISSUE TITLE
[FEATURE] Add ROC approach in benchmark testing and reporting

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/k-NN#398]
**Is your feature request related to a problem?**
Existing approach for kNN performance benchmarking does not give results in form of ROC. This format is de-facto standard in the industry, for example ann-benchamrk project publishes ROC curves for their results - https://github.com/erikbern/ann-benchmarks. 
Currently for kNN there are two benchmarking tools, customized extensions for OpenSearch Benchmark tool and custom scripts that are specific for kNN.

**What solution would you like?**
At least one of existent benchmark tools in kNN need to be able to run and provide results in form of ROC curve or in a form that is ready to be plotted as ROC curve. 
As a bare minimum we need an ability to configure and run indexing and query tests with several different algorithm parameters (m and efConstruction) and collect aggregated results (latencies, recall, throughput etc.).

**Comment by jmazanec15** [comment]
@martin-gaievski what does ROC stand for?

**Comment by jmazanec15** [comment]
Ah okay, I think what that would look like is some kind of wrapper tool around one of our benchmarking tools (preferabaly OSB functionality).

Alternatively, we can run with ann-benchmarks or bigann-benchmarks code for comparison purposes.
