### ISSUE TITLE
Refactor EntryContext to use the Visitor Pattern

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#399]
Currently, when a caller wants to make a native memory allocation, they will configure a NativeMemoryEntryContext with a load strategy and then the load method will use this load strategy to load the entry into native memory.

Instead of this, the NativeMemoryEntryContexts should use the [visitor pattern](https://www.baeldung.com/java-visitor-pattern). Each EntryContext would add a accept(LoadStrategy) class. 

Then, we would create a NativeMemoryEntryVisitor interface that would have visit methods for each entry type. We could then implement a concrete type and initialize it in the NativeMemoryCacheManager.

This would have the following benefits:
1. The only memory elements we would need to expose to the rest of the plugin would be the construction of native memory entry contexts and the get method for the cache manager.
2. We would get rid of singleton classes for each load strategy
3. Reduce the complexity of the implementation of the memory structure. 

Here are some code links for seeing how it is currently done:
1. https://github.com/opensearch-project/k-NN/blob/2.0/src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java#L255
2. https://github.com/opensearch-project/k-NN/blob/2.0/src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java#L50
3. https://github.com/opensearch-project/k-NN/blob/2.0/src/main/java/org/opensearch/knn/index/KNNWeight.java#L135

As part of this, I think we could cleanup the implementation in a couple ways:
1. Separate interfaces from implementations
2. Add builders to entry contexts

@martin-gaievski what do you think?

**Comment by martin-gaievski** [comment]
Overall I think it's a good idea, should make code cleaner. The minor doubt I have is the maintainability, with the "visitor" adding a new  load strategy will be harder. If we do not expect new additions often it's not a big problem.

**Comment by jmazanec15** [comment]
@martin-gaievski I was thinking it would be easier to add a new load strategy. I am going to submit a PR for it and we can see if it makes sense.
