### ISSUE TITLE
Adding support for integration tests with remote cluster.

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/k-NN#427]
With the support of using the remote cluster as an endpoint for the integration test added in the OpenSearch repo. We should add that feature on the Geo repo for below benefits:
1. Provides the testing facilities with a local cluster without depending on the integ test cluster that gets created during the running of these tests.
2. Enabled the capability for adding heavier load integration tests going forward with multi node clusters.

Sample code link: https://github.com/opensearch-project/anomaly-detection/pull/298/files

**Comment by jmazanec15** [comment]
I believe this should be taken care of with https://github.com/opensearch-project/k-NN/pull/266.

**Comment by navneet1v** [comment]
Yes. Thanks for providing the input. Resolving.
