### ISSUE TITLE
[Enhancement] Add integtest.sh to unify the integTest for k-NN in OpenSearch

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/k-NN#45]
**Is your feature request related to a problem? Please describe.**
[Enhancement] Add integtest.sh to unify the integTest for k-NN in OpenSearch

**Describe the solution you'd like**
In order to resolve the issues in ODFE where all plugins integTest saved in one yml,
we propose new OpenSearch solutions where every plugin repo host abstraction layer of integtest.sh
so that all plugins integTest can be run in the same ways with the same commands.

**Describe alternatives you've considered**

**Additional context**

**Comment by dblock** [comment]
Are we set on using this mechanism? We could be running a GitHub action like [this](https://code.dblock.org/2021/06/15/running-github-actions-locally-using-act.html).
