### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/k-NN#451]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @vamshin @sean-zheng-amazon can you please post an update on this branching strategy?
Thank you
@dblock @bbarani @CEHENKLE

**Comment by dblock** [comment]
There should be nothing blocking this rn. To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by naveentatikonda** [comment]
> There should be nothing blocking this rn. To close this issue:
> 
> * [ ]  main is building 3.0
> * [ ]  2.x is building next 2.x, which is currently 2.4.0
> * [ ]  2.3 is building next 2.3, which is 2.3.1
> * [ ]  manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

@dblock our main is pointing to 3.0 and 2.x to 2.4.0. But, as per Barani's comment in opensearch-release channel 2.3.1 release is kept on hold. So, can we go ahead and close this issue ?

**Comment by prudhvigodithi** [comment]
Hey @naveentatikonda as long as your branching is inclined you can close this, there is already an open automation PR https://github.com/opensearch-project/k-NN/pull/558 to increment to 2.3.1, but that being said even if the release is on hold, the increment can still happen right?
@bbarani

**Comment by prudhvigodithi** [comment]
Hey @naveentatikonda as long as you are consistent with branching, you can acknowledge and close this, for `2.3.1` version increment the auto version increment PR is already open https://github.com/opensearch-project/k-NN/pull/558, even though the release kept on hold, we can still continue to increment the 2.3 to 2.3.1 anything stopping?
@bbarani

**Comment by naveentatikonda** [comment]
> Hey @naveentatikonda as long as you are consistent with branching, you can acknowledge and close this, for `2.3.1` version increment the auto version increment PR is already open #558, even though the release kept on hold, we can still continue to increment the 2.3 to 2.3.1 anything stopping? @bbarani

Got it. The Build and other checks failed with an error unable to find the snapshot. I have retried them. Will merge that PR after the checks passed. Thanks!
