### ISSUE TITLE
Standardize branching to match OpenSearch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/k-NN#47]
Coming from [.github#13](https://github.com/opensearch-project/.github/issues/13), standardize release branching to match what [OpenSearch](https://github.com/opensearch-project/OpenSearch) is [doing](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching).

1. Create a `1.0` branch for the OpenSearch 1.0 release, `1.x` branch for next 1.1 release, and use `main` for 2.0 development. Make sure CI is enabled on those.
2. Update your release/branching documentation. If you don't have one, add a RELEASING.md that links to, or has content from [.github/RELEASING.md](https://github.com/opensearch-project/.github/blob/main/RELEASING.md).
3. If you are using a `develop` branch, stop. You should be using the default `main` brach for furthermost, future development. 
4. Delete any merged/stale/develop/feature branches that are no longer in use.
5. Communicate any changes in process to your team.

Refer to [release branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching) for more information.

**Comment by jmazanec15** [comment]
Thanks @dblock, I have 1 question about develop branch in regards to faiss. If we are unsure if it will be ready by 2.0 release, should it still go into the main branch? Or should we not merge into main until we are sure?

I do not see OpenSearch waiting to release 2.0 if a feature on a plugin is not ready yet and I do not think they should. So, from plugin side, assuming that there are several other features inter-mixed in the commits on main branch that are ready for 2.0, this may cause development pains when trying to cut 2.0 branch (i.e. cherry-picking the commits that are ready to go out in 2.0). That being said, what are your thoughts?

**Comment by dblock** [comment]
> Thanks @dblock, I have 1 question about develop branch in regards to faiss. If we are unsure if it will be ready by 2.0 release, should it still go into the main branch? Or should we not merge into main until we are sure?

I think you should make this call. If you think it will most likely be ready, put it in main.
 
> I do not see OpenSearch waiting to release 2.0 if a feature on a plugin is not ready yet and I do not think they should. So, from plugin side, assuming that there are several other features inter-mixed in the commits on main branch that are ready for 2.0, this may cause development pains when trying to cut 2.0 branch (i.e. cherry-picking the commits that are ready to go out in 2.0). That being said, what are your thoughts?

I think the question is really "do we keep features in a feature branch until we're sure we want to release them"? That's on your team to decide. I generally try to shorten development, and reduce scope so that I can ship often, without having to have long lived feature branches that are expensive to maintain. For FAISS, maybe there are pieces of infrastructure that can be merged onto main now, then the amount of potential divergence is reduced.

**Comment by VijayanB** [comment]
Updated branching strategy.
