### ISSUE TITLE
[BUG] model_blob gets too long to show in opensearch-dashboard

### ISSUE THREAD

**Issue by maede-a** [opensearch-project/k-NN#499]
**Describe the bug**
I use knn plugin. I want to use faiss engine with ivf algorithm. I trained a model with train api. I picked nlist=10000.
when I call get model api from opensearch dashboard, my browser crash.
I tried to call get model api with curl and I found out model_blob value in the response is too long to show in opensearch dashboard. I believe model_blob is not necessary in response.

**To Reproduce**
1. Create and index with knn:true, then create a vector field
PUT index-name/_mapping
{
 "properties": {
    "field-name": {
      "type": "knn_vector",
      "dimension": 768
    }
  }
}
2. Insert 1M vector in the field
3. Train a model
POST /_plugins/_knn/models/_train
{
  "training_index": "index-name",
  "training_field": "field-name",
  "dimension": 768,
  "method": {
    "name": "ivf",
    "engine": "faiss",
    "space_type": "innerproduct",
     "parameters":{
            "nlist":10000
     }
  }
}
4. Wait until training completed
5. Call get model api
GET /_plugins/_knn/models/model-id

**Plugins**
knn

**Host/Environment (please complete the following information):**
 - Version 2.1.0

**Comment by jmazanec15** [comment]
To avoid returning model_blob, you can use filter_path. For example:
```
GET /_plugins/_knn/models/model-id/filter_path=model_id,state
```

In terms of returning the model blob, I had mixed feeling about this. On one hand, I think it could help users debug offline, but on the other hand, it can lead to a very large response. With filter_path, you can avoid returning it.

**Comment by maede-a** [comment]
Thank you @jmazanec15!
I also have another question, not related to this issue. But I am curious about it and I didn't find anything in the documentation. When I choose ivf method for knn, what kind of model OpenSearch train?
There are multiple ivf methods in faiss documentation. Which one OpenSearch uses?

**Comment by jmazanec15** [comment]
> When I choose ivf method for knn, what kind of model OpenSearch train?
There are multiple ivf methods in faiss documentation. Which one OpenSearch uses?

Whats going on behind the scenes is a faiss IVF index is being trained. This trained empty index we refer to as a model. It is used to initialize all future segments. Internally, IVF is running k-Means clustering on the training data during the training phase.
