### ISSUE TITLE
Add warmup step to OSB procedures

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#505]
The warmup API is used to load nmslib/faiss indices into native memory before search. In order to avoid costly initial queries, our benchmark procedures should have a step to warmup the indices before search.

**Comment by TrungBui59** [comment]
@navneet1v Can I get assigned to this issue?

**Comment by navneet1v** [comment]
> @navneet1v Can I get assigned to this issue?

Done

**Comment by TrungBui59** [comment]
@navneet1v @jmazanec15 I am quite new to the repo, can you provide a little bit more about the repo's structure and the direction I should look to resolve this issue?

**Comment by navneet1v** [comment]
@TrungBui59 Check this custom refresh step: https://github.com/opensearch-project/k-NN/blob/main/benchmarks/osb/extensions/runners.py#L16-L17

We need to add a step for warmup which hits the warmup API: https://opensearch.org/docs/latest/search-plugins/knn/api/#warmup-operation

**Comment by jmazanec15** [comment]
Closed - already completed in OSB
