### ISSUE TITLE
[BUG] libopensearchknn_nmslib.so missing

### ISSUE THREAD

**Issue by ruria** [opensearch-project/k-NN#508]
Hi,
I´m start playing with KNN plugin, since them my opensearch instance does not start up, It complains:

`java.lang.UnsatisfiedLinkError:  no opensearchknn_nmslib in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib`

Including -Djava.library.path= <OPENSEARCH_HOME>/opensearch-2.1.0/plugins/opensearch-knn/lib new exception is:

`java.lang.UnsatisfiedLinkError: /home/opensearch/opensearch-2.1.0/plugins/opensearch-knn/lib/libopensearchknn_nmslib.so: libopensearchknn_common.so: cannot open shared object file: No such file or directory`

but libopensearchknn_common.so is on <OPENSEARCH_HOME>/opensearch-2.1.0/plugins/opensearch-knn/lib, and it has read permissions.

Any idea?

**Comment by jmazanec15** [comment]
Hi @ruria 

libopensearchknn_nmslib isnt missing, but libopensearchknn_common is not in the PATH. 

Try setting LD_LIBRARY_PATH first:
```
export LD_LIBRARY_PATH=/home/opensearch/opensearch-2.1.0/plugins/opensearch-knn/lib
```

This is kind of annoying to have to set. In the future, I think we could leverage [RPATH](https://en.wikipedia.org/wiki/Rpath) to avoid this.

Here is where we do it in our start script: https://github.com/opensearch-project/opensearch-build/blob/main/scripts/legacy/tar/linux/opensearch-tar-install.sh#L46

**Comment by ruria** [comment]
Thx! It works like a charm.
I configured security plugin (as doc says) and start with bin/opensearch script, I think this was the problem, KNN plugin is not configured there.
