### ISSUE TITLE
[RFC] Filtering in Lucene HNSW KNN

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/k-NN#519]
The purpose of this RFC (request for comments) is to gather community feedback on a new proposal of integrating [k-NN search filtering](https://issues.apache.org/jira/browse/LUCENE-10382) for Lucene HNSW engine into OpenSearch.

### Problem Statement

In many use cases additional filtering functionality can be used on top of k-NN search to produce more relevant results and lower latency searches. In this context we understand filtering as collection of strategies or solutions for reducing size of search space.

Today, it is possible with the k-NN plugin to filter k-NN search, but with significant limitations. One approach is to use the script scoring/painless scripting on a sub-set of documents produced from an earlier stage of the query (see [example](https://opensearch.org/docs/latest/search-plugins/knn/knn-score-script/#getting-started-with-the-score-script-for-vectors)). This approach is akin to running an exact nearest neighbor search on the filtered sub-set. With that being said, exact nearest neighbor search will not scale when the filtered sub-set becomes large. Alternatively, an approximate nearest neighbor (ANN) search can be used in a boolean query with filters. However, the filter will be applied after the nearest neighbor search returns results. In cases where the filter set is small compared to the index, this will lead to the search potentially yielding << k results. Additionally, because the ANN search runs against the entire search space regardless of the filter, performance improvements that the filter provides will be negligible.

### Proposed Solution

In Lucene 9.1, new filter functionality was added to the k-NN query type that efficiently integrates a filter with ANN search. To solve previously mentioned filtering issues, we want to expose this functionality in our k-NN query. 

From a high level, the general strategy Lucene employs is to use the filtered document set throughout the search process to determine whether to use the HNSW algorithm to find the results (avoiding adding the filtered out results) or to fall back to running exact search on the filtered doc set. By doing this, it guarantees results will not be filtered out after the search (preventing the case where the number of results is << k), while also providing the scalability of ANN search. As a side effect of such combined approach Lucene keeps recall equal or higher comparing to existing filterin approach with approximate k-NN search.

#### Algorithm Details

In this section, we go into more details on how the filtering implementation works, but a lot more details can be found in the [Lucene issue](https://issues.apache.org/jira/browse/LUCENE-10382) or directly in the [Lucene code](https://github.com/apache/lucene/blob/60fa19d50938784742be273697c9b38990c3067b/lucene/core/src/java/org/apache/lucene/search/KnnVectorQuery.java#L120). 

Assume we have the following variables:

* _N_ documents in the index
* _P_ documents in the search set after the filter is applied. _P <= N_
* _q_ is the search vector

```
if P <= k
    then do exact k-NN search on P docs
else 
    start HNSW search on N docs (approximate search)
        run search traversal; skip adding docs not in P
        if during the traversal, the number of nodes visited exceeds P
            then interrupt search

    if HNSW search has been interrupted
        then do exact k-NN search on P
    else
        return result of HNSW search
```

#### Limitations

Filtering will work only when Lucene is set as a hnsw engine.

For large values of k, search may show higher latencies. If filtering leaves number of documents greater than k it's still possible that Lucene will switch to exact brute-force k-NN. In such case Lucene will do the search two times - partial approximate search before it got interrupted, and the complete brute-force k-NN on pre-filtered sub-set.

#### Integration with knn query type

We propose to add filter as an object in knn query under name “filter” using OpenSearch [DSL](https://opensearch.org/docs/2.0/opensearch/query-dsl/index/). Example of such request with the filter clause:

```
{
  "size": 7,
  "query": {
    "knn": {
      "my_vector": {
        "vector": [1.4, 3.2, 5.0, 2.6],
        "k": 7,
        "filter": {
            "bool": {
                "must": {
                    "range" : {
                        "level" : {
                            "gte" : 1,
                            "lte" : 5
                        }
                    }  
                },
                "should": [
                    { "term": { "color": "red" }},
                    { "wildcard": 
                        { "color": {
                            "value": "y*w"}
                        }
                    },
                    { "regexp": { "color": "[a-zA-Z]reen" }}
                ],
                "must_not": [
                    { "term": { "active": "false" }}
                ],
                "minimum_should_match" : 1
            }
        }
      }
    }
  }
}
```

We will allow to define filter for k-NN using the field name filter. It’s the same field that is used in other OpenSearch queries with filtering support, e.g. [Boolean queries](https://opensearch.org/docs/latest/opensearch/query-dsl/bool/). Filter for k-NN can be any of query types supported by core OpenSearch, for instance [Boolean query](https://opensearch.org/docs/latest/opensearch/query-dsl/bool/), [Term query](https://opensearch.org/docs/1.3/opensearch/query-dsl/term/), Range query, Regexp query etc. This includes combination of multiple query types or terms under Boolean query, like it’s shown in above example.

#### Early code preview 

Code for this feature is still in development, you can track the progress in the feature branch below: https://github.com/opensearch-project/k-NN/tree/feature/efficient-filtering. Please keep in mind that the code in feature branch may be not stable.

### Feedback Requested

Any general comments about the overall direction are welcome. Some specific questions:

* If you currently using filtering for the k-NN results, how selective are the filters? If we compare number of documents after filtering, typical value for k, and index size then how close are those numbers?

**Comment by song-william** [comment]
Super excited to see work on this!
