### ISSUE TITLE
knn_vector codec minor overhead

### ISSUE THREAD

**Issue by TalRefaeli** [opensearch-project/k-NN#53]
Currently in KNN plugin for OpenSearch 1.0.0 RC1 the knn_vector doc_values codec stores extra bytes for each vector.
The reason is a usage of java object serialization (with ObjectOutputStream and ObjectInputStream) that stores extra bytes at the beginning for indicating which object was serialized, in our case it indicates that the object that is stored is a float array. (See https://docs.oracle.com/javase/8/docs/platform/serialization/spec/protocol.html).

27 bytes is not a lot, but when multiplying by the number of vectors it could be more significant in big indices.

My suggestion is that since we know that we store floats and we know the number of features (dimension), we could store the float array as binary without the extra bytes.

Thanks in advance,
Tal

**Comment by jmazanec15** [comment]
Hi @TalRefaeli 

Thanks for finding this.

The related code can be found [here](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/VectorField.java#L46-L55) and [here](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/KNNCodecUtil.java#L53-L69).

I think this could be refactored to something like this suggestion in [SO question](https://stackoverflow.com/questions/19624161/unsupportedoperationexception-with-converting-byte-to-float/44104399#44104399).

One concern is that this could break backwards compatibility (i.e. user migrates from an old version of the plugin to a new version, and the plugin wouldn't be able to read data from old indices). This may take some thought to prevent this break. One initial thought is to create a new version of the Codec and then to support both.

**Comment by TalRefaeli** [comment]
Yeah, a new codec with backward compatibility sounds like a good and practical solution.
