### ISSUE TITLE
[BUG] The GET _script_language request returns a NullPointerException

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/k-NN#561]
**Describe the bug**
The GET _script_language call returns a NullPointerException:  Cannot invoke "java.util.Set.stream()" because the return value of "org.opensearch.script.ScriptEngine.getSupportedContexts()" is null

**To Reproduce**
1. Either go to the DevTools on Dashboards or use curl
2. Send the GET _script_language request to OpenSearch
4. The response contains a NullPointerException:
`{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : "Cannot invoke \"java.util.Set.stream()\" because the return value of \"org.opensearch.script.ScriptEngine.getSupportedContexts()\" is null"
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : "Cannot invoke \"java.util.Set.stream()\" because the return value of \"org.opensearch.script.ScriptEngine.getSupportedContexts()\" is null"
  },
  "status" : 500
}`
The log:
`| [2022-09-16T13:54:52,502][WARN ][r.suppressed             ] [opensearch] path: /_script_language, params: {pretty=true}
opensearch               | java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "org.opensearch.script.ScriptEngine.getSupportedContexts()" is null
opensearch               |      at org.opensearch.script.ScriptService.lambda$getScriptLanguages$8(ScriptService.java:669) ~[opensearch-2.2.0.jar:2.2.0]
opensearch               |      at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
opensearch               |      at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553) ~[?:?]
opensearch               |      at org.opensearch.script.ScriptService.getScriptLanguages(ScriptService.java:666) ~[opensearch-2.2.0.jar:2.2.0]
opensearch               |      at org.opensearch.action.admin.cluster.storedscripts.TransportGetScriptLanguageAction.doExecute(TransportGetScriptLanguageAction.java:59) ~[opensearch-2.2.0.jar:2.2.0]
opensearch               |      at org.opensearch.action.admin.cluster.storedscripts.TransportGetScriptLanguageAction.doExecute(TransportGetScriptLanguageAction.java:48) ~[opensearch-2.2.0.jar:2.2.0]
`
**Expected behavior**
Expected to get a list of script languages.

**Plugins**
Default list.

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 10

**Additional context**
GET _script_context works as expected

**Comment by dbwiddis** [comment]
> Moved this to k-nn. @dbwiddis what's the fix? (link)

https://github.com/opensearch-project/k-NN/pull/560
