### ISSUE TITLE
Vector efficient math operations for KNN distance functions

### ISSUE THREAD

**Issue by Tradunsky** [opensearch-project/k-NN#617]
**Is your feature request related to a problem? Please describe.**
Exact-KNN distance functions use sub-optimal vector math operations. This can contribute to extra time on high vector dimension distance compute.

**Describe the solution you'd like**
Do you think it is possible to use [Vector API](https://openjdk.org/jeps/417) for math operations in the distance functions?
For example, the following cosine similarity that iterates over each element in both vectors to multiply numbers:
https://github.com/opensearch-project/k-NN/blob/120c4ce57dec7cf524cd681107fced0aeb412592/src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java#L96
could apply vector optimal fused multiply-add instead.

If for the usage of Java Vector API, supported java version is a concern, it could also start with `Math.fma()`.

**Describe alternatives you've considered**
ANN would be an option if pre-filtering supported.

**Additional context**
Much appreciate OpenSearch work on KNN, as it gets bigger demand with ML to relay on vector supporting DBs on distributed computations.

**Comment by dblock** [comment]
Where would we want to configure which distance function to use? Index level options?

**Comment by vamshin** [comment]
Looks like we need OpenSearch core to move to open jdk 19 to use ```Math.fma()```.  Will prioritize once we have this version in core

**Comment by Tradunsky** [comment]
Linking here for visibility:
https://github.com/apache/lucene/issues/12091

This is also implemented in Elasticsearch and dropped latencies by at least 50% in my case.

**Comment by jmazanec15** [comment]
Addressed in #1699
