### ISSUE TITLE
Whitesource security issue failing due to no used nmslib deps

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#662]
Whitesource check in CI failing with dependency vulnerability issues from nmslib. https://github.com/opensearch-project/k-NN/pull/661/checks?check_run_id=10001548361. We do not use these dependencies. Will need to create a issue/PR upstream to fix.

#661

**Comment by jmazanec15** [comment]
Tracking libs that need to get updated in nmslib:
1. httpclient-4.4.1.jar -  /jni/external/nmslib/query_server/java_client/pom.xml (#671, #670 )
2. jquery-3.2.1.js -  /jni/external/nmslib/docs/_static/jquery-3.2.1.js (#669, #667, #664  )
3. jquery-3.2.0.js -  /jni/external/nmslib/docs/_static/jquery-3.2.0.js (#669 #667, #664  )
4. jquery-3.2.1.min.js -  /jni/external/nmslib/docs/api.html (#669, #667, #664  )
5. libthrift-0.11.0.jar - /jni/external/nmslib/query_server/java_client/pom.xml ( #668, #665  )
6. commons-codec-1.9.jar - /jni/external/nmslib/query_server/java_client/pom.xml ( #666 )

Will create an issue over there to fix. For this plugin, we do not use any of these dependencies. They are just inherited b/c of the submodule dependency we take on nmlsib.

**Comment by jmazanec15** [comment]
Fixes:
jquery - upgrade to 3.5.0
httpclient - upgrade to 4.5.13
libthrift - upgrade to 0.16.0 (see #670 )
commons-codec - upgrade to 1.13

**Comment by jmazanec15** [comment]
>  commons-codec - upgrade to 1.13

This will be taken care of by upgrading libthrift

**Comment by naveentatikonda** [comment]
Closing this issue as all the above mentioned libraries have been updated and white check is succeeding.
