### ISSUE TITLE
[RFC] Support Facebook's faiss library as another Approximate k-NN engine

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#70]
## Overview
Over the past year, we have received [a lot of interest](https://github.com/opendistro-for-elasticsearch/k-NN/issues/225) in supporting Facebook’s MIT licensed *[faiss](https://github.com/facebookresearch/faiss)* library, as another Approximate k-Nearest Neighbor (ANN) engine, in addition to *[nmslib](https://github.com/nmslib/nmslib/)*. *faiss* offers a diverse set of algorithms that allow users to easily make tradeoffs between indexing latency, memory usage, query latency, and recall to fit their ANN workload requirements.

Earlier this year, a member of the community made [a contribution](https://github.com/opendistro-for-elasticsearch/k-NN/pull/285) in Open Distro for Elasticsearch for initial *faiss* support. This contribution integrated the *faiss* library into the plugin and added support for *faiss*’s implementation of Hierarchical Navigable Small World (HNSW) graphs. We are building on top of this contribution to support additional *faiss* features like vector quantizers and other ANN search methods.

Supporting *faiss* will allow users to choose from different ANN search methods and algorithms that are not available in *nmslib*. In particular, we are very interested in supporting *faiss*’s quantization methods that can reduce the amount of memory an ANN index requires.

Additionally, while this project focuses on integrating *faiss*, it should also refactor the plugin so that we can support additional ANN libraries and their methods in the future.

We are developing on the [feature/faiss-support](https://github.com/opensearch-project/k-NN/tree/feature/faiss-support) branch and are planning to merge to main once all requirements have been met.

## Problem Statement
Because the k-NN plugin only supports one ANN engine and method, the amount of customization a user can make to achieve a solution to their ANN workload is limited.

Specifically, one problem k-NN plugin users face is that the plugin can consume a significant amount of memory. Currently, the plugin is built on top of *nmslib*’s implementation of HNSW. HNSW is a fast and fairly accurate [ANN method](http://ann-benchmarks.com/). Still, for some workloads, the HNSW algorithm’s memory consumption can be an issue. From [our documentation](https://docs-beta.opensearch.org/search-plugins/knn/performance-tuning/#estimating-memory-usage), each vector will consume approximately `1.1 * (4 * dimension + 8 * M)` bytes. *faiss* implements several different algorithms that can provide ANN search using much less memory at the cost of additional compute during training. By supporting *faiss*, we can let users make memory based tradeoffs in order to achieve the solution that they want.

## Requirements
In the initial phase, the requirements are:
1. Refactor the k-NN plugin to be able to support more than one ANN engine
2. Support *faiss* [composite indices](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes-(composite))
3. Support *faiss*’s [HNSW](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes#indexhnsw-variants) ANN method
4. Support *faiss*’s [Inverted File System](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes#cell-probe-methods-indexivf-indexes) (IVF) ANN method
5. Support *faiss*’s [Product Quantization](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes#indexes-based-on-product-quantization-codes) (PQ) vector quantization method

In the future, we may consider supporting:
1. OpenSearch’s msearch type with *faiss*’s bulk querying functionality
2. Additional *faiss* features, such as preprocessors and post query refinement as well as other ANN methods

## Proposed Solution
In order to support *faiss* in the k-NN plugin, we need to:

1. Refactor the JNI to support additional libraries
2. Add additional API’s and system resources to support ANN methods that require training
3. Enhance the *knn_vector* field type to support multiple engines and methods

### Training Support
Several *faiss* features, such as IVF and PQ, require a training step before indexing can begin. Training takes a set of training vectors and creates a model that these features use to perform their functionalities.

From the plugin perspective, there are two approaches to support training: (1) Train a new model during segment creation with a subset of the segment’s index data and (2) Train a model before indexing can begin and use it to initialize the ANN library index during segment creation.

While the approaches are not mutually exclusive, initially we will only support Approach 2.

Approach 1 is easier to implement, but it significantly increases indexing latency. Every time a new segment is created, a new model needs to be trained. Additionally, because the model is trained with a subset of the segment’s data, it is difficult to guarantee the quantity and quality of the training data.

Approach 2 requires us to add additional APIs and OpenSearch utilities for a user to train a model and connect it to an OpenSearch k-NN index. However, it speeds up indexing and gives the user more control over the model produced. Additionally, it is recommended in the [*faiss* documentation](https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM#general-approach).

#### Model System Index
In order to persist *faiss* trained models and their metadata, we need to create a model system index.

During segment creation, a *GET* call is made to retrieve a model’s binary representation. The model is then used in the JNI layer to initialize the ANN library index. Once initialized, the vectors for the given segment are indexed into the ANN library index. After this completes, the ANN library index file is written to the OpenSearch index’s segment.

![image](https://user-images.githubusercontent.com/19438237/126679063-83095ec5-cf76-4acc-8711-8c9fe85b3c57.png)

#### Train API
In order to support Approach 2, we need to give users the functionality to train a model in their OpenSearch cluster. To do this, we need to add a train API:
```
POST /_plugins/_knn/model/train
{
  "train_index": "train-index-name",
  "train_field": "train-field-name",
  "model_id": "custom-model-id",
  "dimension": 16,
  "method": {
      "name":"ivf",
      "engine":"faiss",
      "space_type": "l2",
      "parameters":{
         "ncentroids":128,
         "coarse_quantizer":{
            "name":"ivf",
            "parameters":{
                "ncentroids":15
            }
        },
        "encoder":{
            "name":"pq",
            "parameters":{
                "code_size":8
            }
        },
      }
  }
}
{
  "status": "SUCCESS",
  "model_id": "custom-model-id"
}
```

This API triggers a training workflow that reads a training set of vectors from another OpenSearch index, creates and trains an ANN library model and then serializes it into the model system index.

![train-e2e2](https://user-images.githubusercontent.com/19438237/126679778-da51d879-e11d-41ae-8e5b-52d1557313dc.png)

#### Upload API
One potential issue with training is that it can be very resource intensive, which could negatively impact an OpenSearch cluster that is processing a heavy workload. So, to unblock users who want to use models that require resource intensive training, we need to also provide an upload API:
```
POST /_plugins/_knn/model/upload
{
    "model_id": "custom-model-id",
    "engine: "engine-of-the-model",
    "dimension": X,
    "space_type": "space-type-of-the-model",
    "model_blob": "some base64 encoded string"
}
{
  "status": "SUCCESS",
  "model_id": "custom-model-id"
}
```

This API triggers a workflow that validates the uploaded model and then serializes it to the model system index.

![upload-rfc3](https://user-images.githubusercontent.com/19438237/126679570-3d8d43ca-9657-468b-ac0f-738b4e52ad38.png)

### knn_vector Field Enhancements
In order for a user to configure an index to use *faiss*, we need to enhance our *knn_vector* field type. Currently, a user creates an index with the following mapping:
```
"my_vector":{
    "type":"knn_vector",
    "dimension": 2,
    "method":{
        "name":"hnsw",
        "engine":"nmslib",
        "space_type":"l2",
        "parameters":{
            "m":44
        }
    }
}
```

To support *faiss* indices that do not require training, we need to add an additional engine. This looks like:
```
"my_vector":{
    "type":"knn_vector",
    "dimension": 2,
    "method":{
        "name":"hnsw",
        "engine":"faiss",
        "space_type":"l2",
        "parameters":{
            "m":44
        }
    }
}
```

For indices that require training, a user needs to have already trained/uploaded the model to the model index. Once they have done this, they can create an ANN OpenSearch index with the following mapping:
```
"my_vector":{
    "type":"knn_vector",
    "model_id": "my_trained_model_template"
}
```

## Feedback
We are interested in any and all feedback you may have. Please do not hesitate to comment!

Specifically, however, we are interested in:
1. What features in *faiss* do you use that you would like to be supported by the k-NN plugin?
2. For your potential use case, if you intend to use a *faiss* index that requires training, would you prefer training offline and using the upload API or training online with the train API? Why?

**Comment by jmazanec15** [comment]
> if a job is /node-a/train-jobs/job-a, what would a get of /node-b/train-jobs/job-a return?

In this case, no results would be returned. A job is bound to a node, however a model is not.

**Comment by jmazanec15** [comment]
@wnbts I decided to update APIs to center around model resource. I felt that having a separate model resource and train jobs resource did not make sense. Please take a look at the update if you get time.

**Comment by wnbts** [comment]
The new version also makes sense to me! I raise some details for discussion.

```
{
    "state": keyword,
    "created_timestamp": date,
    "description": keyword, 
    "error": keyword,
    "model_blob": binary,
    "engine": keyword,
    "space_type": keyword,
    "dimension": int
} 
```
1. Why not add model id to the resource body?

**Comment by wnbts** [comment]
```
GET /_plugins/_knn/models/{model_id}?<filter_field_1>&<filter_field_2>

{
    "my_model_id": {
        "state": "CREATED",
        "created_timestamp": "10-31-21 02:02:02",
        "description": "Model trained with dataset X", 
        "error": "",
        "model_blob": "cdscsacsadcsdca",
        "engine": "faiss",
        "space_type": "l2",
        "dimension": 128
    },
    ...
} 
```
1. Getting a single resource can be separated from searching resources, i.e. 
for getting a single resource
```
GET /_plugins/_knn/models/{model_id}
{
    "model_id" : {model_id}
    "state": "CREATED",
    "created_timestamp": "10-31-21 02:02:02",
    "description": "Model trained with dataset X", 
    "error": "",
    "model_blob": "cdscsacsadcsdca",
    "engine": "faiss",
    "space_type": "l2",
    "dimension": 128
}
```
for searching model resources, if needed
```
GET /_plugins/_knn/models/_search?size=10
{
    'query' : {...}
}

[
    {
        'model_id' : 'model_id_1',
        ....
    },
    {
        'model_id' : 'model_id_2',
        ...
    }
]
```

**Comment by wnbts** [comment]
```
PUT /_plugins/_knn/models/<model_id>/_train?preference=<node_id>
```

`preference` might change to a more specific name such as `prefer_nodes` to allow other preferences in the future such as timeout or retry.

**Comment by jmazanec15** [comment]
>     1. Why not add model id to the resource body?

Right, in the mapping, it is implicitly defined as the document id. That being said, I think in the responses, it makes sense to contain the id. I will update.

>     1. Getting a single resource can be separated from searching resources, i.e.
>        for getting a single resource
> 

Might have been misinterpreted. filter_field is meant to filter the items returned in the body. This is similar to how GET calls work: https://opensearch.org/docs/opensearch/rest-api/document-apis/get-documents/#url-parameters.

That being said, GET calls take a "source_includes" param. I could refactor to this.

>     1. `preference` might change to a more specific name such as `prefer_nodes` to allow other preferences in the future such as timeout or retry.
> 
>     2. `PUT` might change to `POST` since it's not putting a resource.

Preference also follows opensearch convention: https://opensearch.org/docs/opensearch/rest-api/document-apis/get-
documents/#url-parameters

I thought `PUT` made sense when the resource id is being passed and the resource is being created. When the resource id is not passed, I made it `POST`

**Comment by wnbts** [comment]
> > ```
> > 1. Getting a single resource can be separated from searching resources, i.e.
> >    for getting a single resource
> > ```
> 
> 
> Might have been misinterpreted. filter_field is meant to filter the items returned in the body. This is similar to how GET calls work: https://opensearch.org/docs/opensearch/rest-api/document-apis/get-documents/#url-parameters.

Yeah, I misinterpreted the api. The input looks good then. The output can just be the same body used in PUT/POST.

> Preference also follows opensearch convention: https://opensearch.org/docs/opensearch/rest-api/document-apis/get-
> documents/#url-parameters

I see, preference is a convention. 

> I thought `PUT` made sense when the resource id is being passed and the resource is being created. When the resource id is not passed, I made it `POST`

The difference is subtle. I see the request is made to id/_train not to id and is therefore not a standard put. Or, a request to id/a/b would be put rather than post. So having post here can make the train api simpler to users without getting into those differences.

**Comment by jmazanec15** [comment]
> The difference is subtle. I see the request is made to id/_train not to id and is therefore not a standard put. Or, a request to id/a/b would be put rather than post. So having post here can make the train api simpler to users without getting into those differences.

I see. I will update to POST. Also, I will add _search API to get multiple models.
