### ISSUE TITLE
[FEATURE] Hybrid search using keyword matching and kNN

### ISSUE THREAD

**Issue by rhvaz** [opensearch-project/k-NN#717]
**Is your feature request related to a problem?**
I would like to search against multiple text fields and a kNN vector. Currently I can only filter the results based on keyword matching against the text fields and then re-rank them using vector metrics such as cosine similarity or l2 norm. This means I miss out on many relevant candidates.

**What solution would you like?**
This solution from ES https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#_combine_approximate_knn_with_other_features

**What alternatives have you considered?**
I could do two distinct queries to the same index and add logic to rank the final results, but this is quite messy and not good for latency.

**Comment by navneet1v** [comment]
@rhvaz 
Hi,
As per my understanding we already have this in k-NN. Please find a sample query below which combines the keyword search with K-NN Search. Also please check this k-NN painless extension for more details on updating the K-NN scores: https://opensearch.org/docs/latest/search-plugins/knn/painless-functions/.

A simple hybrid query

```
{
  "size": 10,
  "from": 0,
  "query": {
    "bool": {
      "should": [ 
        {
          "function_score": {
            "query": {
              "match_all": {} // This can be any query you want to run
            }
          },
          "script_score": {
            "script": {
              "params": {
                "weight": 10 // any value that you want to use.
              },
              "source": params.weight * _score"
            }
          }
        },
        {
          "function_score": {
            "query": {
              "knn": {
                "my_vector": {
                  "vector": [],
                  "k": 10
                }
              }
            }
          },
          "script_score": {
            "script": {
              "params": {
                "weight": 10 // any value you want to use.
              },
              "source": "params.weight * _score"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by navneet1v** [comment]
@rhvaz On doing some deep-dive on the [proposed solution](https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#_combine_approximate_knn_with_other_features), the way ES has implement the K-NN search and the way OpenSearch has implemented the K-NN search is very different. The ES K-NN clause is outside the main query clause and they uses search type as DFS search type to first gather the results for K-NN Query at Coordinator Node level and then pass them along for text search at shard level.

But in OpenSearch, as we have implemented the K-NN clause inside the query the clause the full query object is passed to shards and filtering happens at shard level. 


**New Proposed Solution:**
I am currently working on a generic solution, which solve the problems mentioned by you and also provided in this issue. https://github.com/opensearch-project/OpenSearch/issues/4557. I will update the RFC once I have some concrete approach. 

In the meanwhile please add some more details about your use case which will help us prioritizing the work.

**Comment by rhvaz** [comment]
Sure @navneet1v! I would say one of the main use cases is to provide good search results even for small queries. 

When a consumer starts typing the name of a product or category if we simply do semantic search using kNN the results are poor. If we combine that with keyword matching we can provide good recommendations for any query length. 

I think this has applications in multiple e-commerce sites if people are looking to build a search product using OpenSearch.

**Comment by navneet1v** [comment]
Hi @rhvaz thanks for the support.

Have you tried using this type of query:
```
{
 "query": {
    "bool": {
      "should": [
        {
          // text based query
        },
        {
          // k-NN query
        }
      ]
    }
  }
}

```

Example:
```
{
 "size": 10,
 "query": {
    "bool": {
      "should": [
        {
          "match": {
            "summary": "smart tv"
          }
        },
        {
          "knn": {
            "text_vector": {
              "vector": [2, 3, 5, 6],
              "k": 10,
              "_name": "knn"
            }
          }
        }
      ]
    }
  }
}
```
If yes, I want to know problem did you saw by using above query, where the scores of K-NN and text-match queries are getting combined via bool query at per shard level.

**Comment by navneet1v** [comment]
Hi @rhvaz I am closing this issue as the work to do the hybrid search which includes:
1. Combining score at Corpus level.
2. Normalization Scores before combining the scores from 2 different queries.

is being taken care via this feature request. https://github.com/opensearch-project/neural-search/issues/123 . I will add more details on that issue going forward. Please do a +1 on the feature.
