### ISSUE TITLE
[BUG] reindex fails with "search_context_missing_exception"

### ISSUE THREAD

**Issue by PavelArzhaev** [opensearch-project/k-NN#746]
**What is the bug?**
Reindex of the extensive (~500Gb) knn index fails with the reason stated "all shards failed" and type "search_phase_execution_exception" for the task and reason "No search context found for id [...]" and type "search_context_missing_exception" for indices.

**How can one reproduce the bug?**
1. Create knn index_1 (dimension: 512, engine: "lucene", space_type: "cosinesimil", ef_construction: 32, M: 64, number_of_shards: 16, full info in the additional context)
2. Upload 40M vectors to index_1
3. Create knn index_2 (dimension: 512, engine: "lucene", space_type: "cosinesimil", ef_construction: 256, M: 128, number_of_shards: 32, full info in the additional context)
4. Run reindex from index_1 to index_2 (I tried it both with default source "size" and "size": 10).
5. After some time observe an error.

**What is the expected behavior?**
Reindex finishes successfully.

**What is your host/environment?**
OpenSearch 2.3 deployed using "Amazon OpenSearch Service".

**Do you have any additional context?**
index_1 info:
```
{
	"index_1": {
		"aliases": {},
		"mappings": {
			"properties": {
				"vector": {
					"type": "knn_vector",
					"dimension": 512,
					"method": {
						"engine": "lucene",
						"space_type": "cosinesimil",
						"name": "hnsw",
						"parameters": {
							"ef_construction": 32,
							"m": 64
						}
					}
				}
			}
		},
		"settings": {
			"index": {
				"number_of_shards": "16",
				"provided_name": "index_1",
				"knn": "true",
				"number_of_replicas": "0"
			}
		}
	}
}
```
index_2 info:
```
{
	"index_2": {
		"aliases": {},
		"mappings": {
			"properties": {
				"vector": {
					"type": "knn_vector",
					"dimension": 512,
					"method": {
						"engine": "lucene",
						"space_type": "cosinesimil",
						"name": "hnsw",
						"parameters": {
							"ef_construction": 256,
							"m": 128
						}
					}
				}
			}
		},
		"settings": {
			"index": {
				"number_of_shards": "32",
				"provided_name": "index_2",
				"knn": "true",
				"number_of_replicas": "0"
			}
		}
	}
}
```
Reindex task info:
```
{
	"completed": true,
	"task": {
		"node": "...",
		"id": ...,
		"type": "transport",
		"action": "indices:data/write/reindex",
		"status": {
			"total": 0,
			"updated": 0,
			"created": 0,
			"deleted": 0,
			"batches": 0,
			"version_conflicts": 0,
			"noops": 0,
			"retries": {
				"bulk": 0,
				"search": 0
			},
			"throttled_millis": 0,
			"requests_per_second": 0,
			"throttled_until_millis": 0,
                },
		"description": "reindex from [index_1] to [index_2]",
		"start_time_in_millis": ...,
		"running_time_in_nanos": 8874899582582,
		"cancellable": true,
		"cancelled": false,
		"headers": {}
	},
	"error": {
		"type": "search_phase_execution_exception",
		"reason": "all shards failed",
		"phase": "query",
		"grouped": true,
		"failed_shards": [
			{
				"shard": -1,
				"index": null,
				"reason": {
					"type": "search_context_missing_exception",
					"reason": "No search context found for id [...]"
				}
			},
			{
				"shard": -1,
				"index": null,
				"reason": {
					"type": "search_context_missing_exception",
					"reason": "No search context found for id [...]"
				}
			},
                         ...
                 ],
		"caused_by": {
			"type": "search_context_missing_exception",
			"reason": "No search context found for id [...]"
		},
	}
}
```

**Comment by jmazanec15** [comment]
Hi @PavelArzhaev, it looks like it might be related to time out occurring during reindexing. I found an old related elasticsearch issue on it: https://discuss.elastic.co/t/problem-when-reindexing-large-index/117421. 

That being said, did the reindex partially succeed? If so how many docs?

One option might be to break up the reindex into multiple slices: https://opensearch.org/docs/2.5/api-reference/scroll/.

**Comment by PavelArzhaev** [comment]
Thank you for the response, @jmazanec15 !
I'll try the scroll reindex.
Yes, it was partially successful, right now there are 24332577 docs with 319 GB storage size, but the index is red.

**Comment by jmazanec15** [comment]
Maybe try 500 scroll size. Also, what is the refresh interval?

**Comment by PavelArzhaev** [comment]
Thank you!
The refresh interval was either disabled or 1s in 2 experiments
