### ISSUE TITLE
[BUG] different recall for lucene and nmslib, using same HNSW parameters

### ISSUE THREAD

**Issue by PavelArzhaev** [opensearch-project/k-NN#748]
**What is the bug?**
2 knn indexes with different engines (lucene and nmslib) perform differently in terms of recall

**How can one reproduce the bug?**
1. Create index_1 (engine: nmslib, m: 64, ef: 32, ef_search=100, 1 shard, 1 replica), and upload 100k 512-dim vectors, force merge it to 10 segments.
2. Create index_2 (engine: lucene, m: 64, ef: 32, ef_search is hardcoded to equal k=100, 1 shard, 1 replica), and upload 100k 512-dim vectors, force merge it to 10 segments.
3. Perform 1000 knn-search requests to index_1 (size: 100, k=100), and measure recall.
4. Perform 1000 knn-search requests to index_2 (size: 100, k=100), and measure recall.
5. Recalls for index_1 and index_2 are far from equal (0.92 vs 0.76).

**What is the expected behavior?**
Recalls are semi-equal

**What is your host/environment?**
 OpenSearch 2.3 deployed using "Amazon OpenSearch Service", 8 r6gd.xlarge.search data nodes.

**Comment by martin-gaievski** [comment]
Hi @PavelArzhaev
Recall is not expected to be equal between nmslib and lucene. Even though both implement same HNSW algorithm, implementation is quite different. From our tests lucene recall goes down significantly with lower ef_construction values comparing to nmslib, but lower value of m is not a problem. If you want to get higher recall values on lucene I would recommend to start with default param values m = 16, efc = 100.

**Comment by PavelArzhaev** [comment]
Got it, thank you for the advice!
