### ISSUE TITLE
[BUG] segments are not merging

### ISSUE THREAD

**Issue by PavelArzhaev** [opensearch-project/k-NN#769]
**What is the bug?**
There are a lot of small segments which are not merged either automatically or via forcemerge. Instead, the number of segments stays the same (forcemerge returns "success").

**How can one reproduce the bug?**
1. Create knn index (dimension: 512, engine: "lucene", space_type: "cosinesimil", ef_construction: 128, M: 64, number_of_shards: 24), enable refresh_interval (1s).
2. Upload 30M vectors to the index.
3. Execute forcemerge (either with default max_num_segments or any custom value, ~90%, ~50% of existing segments, 10).

**What is the expected behavior?**
The number of segments lowers.

**What is your host/environment?**
OpenSearch 2.3 deployed using "Amazon OpenSearch Service".

**Do you have any additional context?**
Visualization of segment sizes in mbs (x=segments, y=shards). As one can see, there are a lot of segments small enough to be merged.
<img width="698" alt="Screenshot 2023-02-17 at 18 23 07" src="https://user-images.githubusercontent.com/8198844/219723104-d619d952-504a-491d-b185-ad6f27a84d0a.png">

**Comment by jmazanec15** [comment]
Hi @PavelArzhaev `max_num_segments` will give the number of segments at the shard level, not index level. So for the above graph, if max_num_segments is set to 10, there will be at max 10 segments per shard.

**Comment by PavelArzhaev** [comment]
Thank you!
