### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/k-NN#775]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the k-NN repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| k-NN | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | Certificate of Origin, Link Checker, Documentation Request, Benchmarking Tool, Custom Benchmarking Tool | https://github.com/opensearch-project/k-NN/issues/775 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by navneet1v** [comment]
@scrawfor99 
Apart from this, we have used OpenSearch Benchmarks to do the benchmarking for this repo for every release. Probably this can be a thing that can be added for all the repos.

**Comment by scrawfor99** [comment]
Hi @navneet1v, thank you for following up. I did not realize you had your own benchmarking tool. That sounds like a good option for something that could be included elsewhere as well. I will make a note of this.

**Comment by navneet1v** [comment]
@scrawfor99 just to clarify, we are using OpenSearch Benchmarking tool and our own created tool to do the benchmarking. Both of them are serving different purpose. Ideally we want to use one which is OpenSearch Benchmarks, but given that OpenSearch Benchmarks doesn't support custom metrics we had to create another tool.

**Comment by scrawfor99** [comment]
Hi @navneet1v, thank you for the clarification. I will make sure to update the notes to show this distinction. I appreciate your follow-up.
