### ISSUE TITLE
[BUG] Snapshot build doens't produce -SNAPSHOT artifact

### ISSUE THREAD

**Issue by dblock** [opensearch-project/k-NN#78]
**Describe the bug**

Coming from https://github.com/opensearch-project/opensearch-build/issues/179, the build with `-Dbuild.snapshot=true` doesn't produce snapshot outputs.

**To Reproduce**

```
./gradlew assemble --no-daemon --refresh-dependencies -DskipTests=true -Dopensearch.version=1.1.0-SNAPSHOT -Dbuild.snapshot=true
```

Creates `opensearch-knn-1.0.0.0.zip`.

**Expected behavior**

Expected `opensearch-knn-1.0.0-SNAPSHOT.zip`.

Let's use this issue to also change CI on main to depend on OpenSearch 1.x.

**Comment by vamshin** [comment]
@dblock I do not think this is related to k-NN? Should be moved to job scheduler/Alerting team?

**Comment by dblock** [comment]
> @dblock I do not think this is related to k-NN? Should be moved to job scheduler/Alerting team?

I don't think so. When I build _this_ project I want to be able to produce a -SNAPSHOT build that will have a dependency on a -SNAPSHOT version of any of its dependencies, not the release versions thereof.

**Comment by dblock** [comment]
> @dblock I do not think this is related to k-NN? Should be moved to job scheduler/Alerting team?

Sorry, I messed up in copy-paste. Updated the issue with the problem with k-nn, it doesn't produce the correct output name.
