### ISSUE TITLE
Support Lucene HNSW merge optimization

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#785]
## Description

In Lucene, in https://github.com/apache/lucene/pull/12050, an optimization was added to create a new segment HNSW graph by initializing the graph from the largest graph without any deletes from the collection of segments-to-be-merged. Also, see https://github.com/apache/lucene/issues/11354 for related benchmarks. This will speed up merge operations for larger graphs.

This change will go out in Lucene 96, which we will pick up by default - we wont have to make any code changes. Once we are able to test this change in OpenSearch, we should run performance tests to measure benefit.

**Comment by martin-gaievski** [comment]
With 2.8 k-NN received Lucene 9.6 with the mentioned fix, performance test is completed so we can check on changed numbers. Perf results added to release issue: https://github.com/opensearch-project/k-NN/issues/905
