### ISSUE TITLE
Nested field type support for ANN search

### ISSUE THREAD

**Issue by EricJohanssoon** [opensearch-project/k-NN#797]
I have a question regarding if a nested field type is supported for ANN (Approximate Nearest Neighbor) in OpenSearch? I’ve tried to find more info in the docs about [ANN search](https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/) as well as about [Nested field type](https://opensearch.org/docs/latest/opensearch/supported-field-types/nested/) but can’t find anything relevant? 

Further, I've found an [issue](https://github.com/elastic/elasticsearch/issues/86787) relating to a similar feature for elasticsearch that does not seem to be solved. 

Thanks!

**Comment by navneet1v** [comment]
Hi @EricJohanssoon The nested field type support is present in OpenSearch. Please ignore the Elastic Search issue. The implementation of ANN in Elastic And OpenSearch is different. 

Example to create nested Object:

```
PUT my-knn-index-10
{
  "settings": {
    "index": {
      "knn": true,
      "knn.algo_param.ef_search": 100
    }
  },
  "mappings": {
    "properties": {
      "nestedObject": {
          "type": "nested",
          "properties": {
            "my_vector1": {
            "type": "knn_vector",
            "dimension": 2,
            "method": {
              "name": "hnsw",
              "space_type": "l2",
              "engine": "nmslib",
              "parameters": {
                "ef_construction": 128,
                "m": 24
              }
            }
          }
        }
      }
    }
  }
}
```


Please let us know if you have any more question.

**Comment by navneet1v** [comment]
Resolving the issue, as nested fields for K-NN is supported in OpenSearch
