### ISSUE TITLE
[FEATURE] Support byte sized vector in Lucene engine

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/k-NN#812]
**Is your feature request related to a problem?**
Currently vectors are represented as floats(4 Bytes) for each dimension. This could lead to large storage and memory requirements to construct/load/save/search graphs and at scale becomes costly and also hard to manage the cluster requirements. In some cases, customers prefer to reduce the storage/memory foot prints at the cost of loosing tolerable recall.    

**What solution would you like?**
We could provide Byte sized vectors that can use one Byte per dimension instead of current 4 Bytes using the [ByteVector](https://lucene.apache.org/core/4_1_0/analyzers-common/org/apache/lucene/analysis/compound/hyphenation/ByteVector.html) feature of Lucene. By providing quantization techniques we could let the floats convert to Int[-128 to 127] at loss of some precision and hence provide reduction to storage and memory requirements

**Comment by navneet1v** [comment]
If you are interested in this feature, please do a +1. If possible please leave a comment about your usecase.
