### ISSUE TITLE
[Campaign] Replace Map, List, and Set in org.opensearch.common.collect with java.util references

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/k-NN#815]
**Is your feature request related to a problem?**
Coming from https://github.com/opensearch-project/OpenSearch/issues/6609. The listed classes have already been deprecated as a part of 2.7 and will be dropped with 3.0 release.

**What solution would you like?**
Replace instances of Map, List and Set from `org.opensearch.common.collect` with the corresponding `java.util` references

**Do you have any additional context?**
- [ ] https://github.com/opensearch-project/k-NN/blob/e1d2e45ff04dab2624ddd0f300b407f26fdb8f61/src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java#L35

**Comment by kotwanikunal** [comment]
@naveentatikonda Looks like the changes were merged. Can we close this issue out?

**Comment by naveentatikonda** [comment]
@kotwanikunal I'm waiting on the backport PR to be merged to 2.x branch https://github.com/opensearch-project/k-NN/pull/825.
Will close the issue once it is merged.
