### ISSUE TITLE
Combine approx-knn with other features

### ISSUE THREAD

**Issue by vkc12uec** [opensearch-project/k-NN#818]
**Is your feature request related to a problem? Please describe.**
We actually want ES queries to return both knn and usual ES-query results. Something like this - https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#_combine_approximate_knn_with_other_features

I read on OpenSearch documentation but can't find anything similar.

**Describe the solution you'd like**
Can we adopt the similar solution like official ES?

**Describe alternatives you've considered**
We current make two queries and choose the best ones for our product. But we think using single query approach would be better.

**Additional context**

**Comment by navneet1v** [comment]
@vkc12uec I don't think so both results are returned separately in ES. This is what I saw in documentation.

```
This search finds the global top k = 5 vector matches, combines them with the matches from the match query, and finally returns the 10 top-scoring results. The knn and query matches are combined through a disjunction, as if you took a boolean or between them. The top k vector results represent the global nearest neighbors across all index shards.
```

To give more details:
the way k-NN works in OpenSearch is little different I explained same on this forum question: https://forum.opensearch.org/t/k-nn-multiple-field-search-in-opensearch/12521/5?u=navneet. You can check this out.

If you want to combine k-NN and non-k-nn results you can use bool query clause. If you need to  documents matching one or more wrapped queries, then you can use dis_max and put your K-NN and non-k-NN queries there.

Example of Bool Query:

```
{
    "query": {
        "bool": {
            "should": [
                {
                    "knn": {
                      "my_vector": { // vector field name
                        "vector": [2, 3, 5, 6],
                        "k": 2
                      }
                    }
                },
                {
                    "term": {
                        "passage_text": "welcome"
                    }
                }
            ]
        }
    }
}
```
I hope this ans your question.

**Comment by dblock** [comment]
I think it's a good idea. @vkc12uec care to provide some examples of current request/response vs. what you'd like them to be? I'll move this to the k-nn repo.

**Comment by navneet1v** [comment]
@dblock the feature is already supported with k-NN plugin.
