### ISSUE TITLE
Set knn lib version based on plugin version

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/k-NN#82]
Currently, we hardcoded knn plugin version as 1.1.0.0. This should be updated to plugin's build version.

**Comment by peterzhuamazon** [comment]
Code example?

**Comment by peterzhuamazon** [comment]
I agree that this can be grep from the plugin build version, as long as it still produce correct artifact zips.
The DEB/RPM does not need any reference for hardcoded versions anymore.

**Comment by jmazanec15** [comment]
Code example: https://github.com/opensearch-project/k-NN/blob/main/jni/CMakeLists.txt#L193-L235.

We use to use CPack to build deb/rpm of lib. But if we dont need this functionality anymore, I think the versioning in cmake can be removed. Just wanted to confirm with you that this is not needed for RPM/DEB OpenSearch bundle build.
