### ISSUE TITLE
Support for fp16 knn_vector

### ISSUE THREAD

**Issue by kalkarth** [opensearch-project/k-NN#830]
**Is your feature request related to a problem?**
We want to leverage open source indexing for our dense retrieval scenarios. Our vectors are long (~1K dimension) and is fp16. Storing them as fp32 occupies more space (as we plan to index billions of points) and also makes L2 measure comparison potentially expensive. 

**What solution would you like?**
Support for fp16 for all knn related features (indexing, scoring (both exact and hnsw))

**What alternatives have you considered?**
Vespa, Qdrant

**Do you have any additional context?**

**Comment by navneet1v** [comment]
If this is a feature you are interested in please do a +1.

**Comment by kalkarth** [comment]
Hi, It certainly would be useful. We however havent quantified how the loss of accuracy going down to 8 bits is going to affect our e2e scenarios. We have concrete data that fp16 doesn't cause much loss for us in accuracy. We could evaluate and get back to you. When is this feature likely to be ready?

**Comment by navneet1v** [comment]
> Hi, It certainly would be useful. We however havent quantified how the loss of accuracy going down to 8 bits is going to affect our e2e scenarios. We have concrete data that fp16 doesn't cause much loss for us in accuracy. We could evaluate and get back to you. When is this feature likely to be ready?

Awesome. I understand the concerns around precision and accuracy loss. We will also be doing the experiments on our side to compare 8-bit with current implementation. On timeline part, the 8-bit is planned for 2.9 which is [planned to release on July 18,2023](https://opensearch.org/releases.html). You can follow this issue #812 and if you can do a +1 on the issue that will be great.

**Comment by hdhalter** [comment]
Hi @vamshin - Can you please add this issue to the unified scorecard project so I can tie the doc issue to it (assuming #5038 covers this feature). Thanks!
