### ISSUE TITLE
Failure to delete model when model is training should not return 200

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#831]
Currently, when we try to delete a model while it is training, we block the request:
```
curl -X DELETE "localhost:9200/_plugins/_knn/models/my-model3?pretty"
{
  "model_id" : "my-model3",
  "result" : "failed",
  "error" : "Cannot delete model \"my-model3\". Model is still in training"
}
```
However, this request returns a 200 response code, even though it failed to delete the resource.

```
curl -I -X DELETE "localhost:9200/_plugins/_knn/models/my-model3"
HTTP/1.1 200 OK
```

I believe that this should throw a 409 conflict error code.

**Comment by navneet1v** [comment]
Closing this issue as the PR is merged.
