### ISSUE TITLE
[Flaky test] Task :qa:rolling-upgrade:testAgainstOneThirdUpgradedCluster FAILED 

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#884]
See action here: https://github.com/opensearch-project/k-NN/actions/runs/4805283415/jobs/8565098796?pr=878

**Comment by jmazanec15** [comment]
Related #878

**Comment by navneet1v** [comment]
@jmazanec15 can we resolve this issue? I don't think we are seeing similar flaky tests now.

**Comment by jmazanec15** [comment]
yeah I guess logs are gone anyway
