### ISSUE TITLE
[BUG] [Severity Blocker] Facing Non-Determenistic results when executing approximate knn queries on Indices that have more than 1 replica

### ISSUE THREAD

**Issue by adnan529** [opensearch-project/k-NN#939]
**What is the bug?**
A clear and concise description of the bug.

**[ Severity Blocker ]**
We are using Lucene hnsw index on opensearch 2.4 and facing non-determenistic results when executing approximate knn queries on indices that have 1 or more replicas.
Example: when executing the same query multiple times with "size" set to 108 and "k" set to 108 we are expected to get 108 unique document ids no matter how many requests we send but in fact this value is anywhere from 108-160 or even reaching 180 of total unique document ids. Issue doesn't persist when index has 0 replicas

**How can one reproduce the bug?**
- Create lucene knn index of at least 10k documents size and at least 1 replica
- Run query for some random vector multiple times (e.g 100 times) with size of 108, and combine document ids of results 

**What is the expected behavior?**
- Results should be more deterministic in a range of 108-120.

**What is your host/environment?**
- OS: amazon linux
- Version Opensearch 2.4

**Do you have any additional context?**
Add any other context about the problem.

- Dimensionality of index is 768. Cluster is having at least 1 replica.

**Settings**
```
{
  'ann_parameters': {
    'engine': 'lucene',
    'space_type': 'cosinesimil',
    'name': 'hnsw',
    'parameters': {'ef_construction': 128, 'm': 16}},
  'model_properties': {
    'dimensions': 768},
  'normalize_embeddings': True,
 }
 'number_of_shards': 24,
 'number_of_replicas': 3
}
```

**Comment by vamshin** [comment]
@adnan529 could you forcemerge to one segment and retry? Also 2.4 version had some performance issues which we fixed in 2.5 version for Lucene engine, do you want to upgrade to 2.5?

```
curl -X POST "localhost:9200/myindex/_forcemerge?max_num_segments=1&pretty"
```

**Comment by tomhamer** [comment]
Is it possible though that that will destabilise the cluster? we are running with quite large shards @vamshin

**Comment by adnan529** [comment]
@vamshin we expect indexing after the forcemerge and this will create newer segment again.

**Comment by jmazanec15** [comment]
One recommendation for this would be to use segment replication which is GA now.
