### ISSUE TITLE
[BUG] Fixed jni test and compile error

### ISSUE THREAD

**Issue by luyuncheng** [opensearch-project/k-NN#941]
**What is the bug?**
when i try to compile and test jni with main branch. i see the following error:

```
release/libopensearchknn_faiss.so: undefined reference to `_gfortran_compare_string'
release/libopensearchknn_faiss.so: undefined reference to `_gfortran_concat_string'
```
```
jni/tests/test_util.h:111:48: error: ‘idx_t’ is not a member of ‘faiss::Index’
```

i think this because `faiss` update to new branch,

**How can one reproduce the bug?**
compile the main branch

**What is your host/environment?**
 - OS:  IOS and Linux

- RP: #940

**Comment by navneet1v** [comment]
@vamshin this is already taken care by @luyuncheng . We need another approval on his PR.

**Comment by navneet1v** [comment]
This PR: https://github.com/opensearch-project/k-NN/pull/951 resolves this issue
