### ISSUE TITLE
[FEATURE] Support for approximate search using hamming distance

### ISSUE THREAD

**Issue by gilamsalem** [opensearch-project/k-NN#949]
**Is your feature request related to a problem?**
I have a large data set (>500M) of binary data (64 bits) which I would like to search for the KNN based on hamming distance.

**What solution would you like?**
I would like to achieve the capability of running approximate search on binary data using hamming distance.

**What alternatives have you considered?**
I used the script score exact search with hammingbit, but the search is slow for my dataset.

**Do you have any additional context?**
Seems like the native faiss library supports binary index using hamming distance:
https://github.com/facebookresearch/faiss/wiki/Binary-indexes

**Comment by jmazanec15** [comment]
Thanks @gilamsalem. Will close in favor of #81
