### ISSUE TITLE
Searching for irrelevant data also returns results.

### ISSUE THREAD

**Issue by ankitas3** [opensearch-project/k-NN#994]
Currently (using nmslib) while searching for any vector, number of results returned are always the same which are more than the mentioned k(returning from each shard/segment)

In case of incorrect or vector not at all related to the data indexed, the behaviour remains the same. Whereas, the expected would be to return no results.

Can we have a field to accept minimum similarity score to return only results having score more than the minimum similarity score, just like the one provided in [ElasticSearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#_search_knn_with_expected_similarity)  
Or a range, as in how close the scores of the results being returned should be to the best matched result, so as to return less results.

**Comment by ankitas3** [comment]
@navneet1v Currently my requirement is to minimise the result set while using kNN by removing the irrelevant results. And also to return no results in case the results are not at all relevant. 
For this as suggested by @juntezhang I used min_score as 0.4. I also tried testing with different min scores but that did not work well. 

Here, I have been getting data even when searching for text that makes no sense(Eg: khgcvyuui) or text that does not lie in the dataset, having max scores -- 0.46
Here setting a score say 0.47 will remove results for such keywords but will also not return results when the text is correct but the whole intent of the query does not match up well with the results. 

My only concern now is how should this min_score be determined. Or if there is any other way to achieve this.

**Comment by savanbthakkar** [comment]
@navneet1v  @juntezhang 
We are facing the same issue with OpenSearch neural search and in production environment, users are continuously adding more records and that may change minimum desired score continuously. So, there is no way to come up with a standard minimum score.
Any solution to this problem would be greatly appreciated, as I am sure many customers are leaning towards neural plugin!

**Comment by vamshin** [comment]
I believe this feature should address the problem https://github.com/opensearch-project/k-NN/issues/814. But what should the exact distance/score to be passed as filter of tricky.

**Comment by junqiu-lei** [comment]
Closing it for now as this issue can be resolve by `min_score` radial search feature https://github.com/opensearch-project/k-NN/issues/814
