### ISSUE TITLE
Failed to build synonyms 

### ISSUE THREAD

**Issue by aishwaryabajaj-54** [opensearch-project/k-NN#998]
Facing Failed to build synonyms issue while creating a new index

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to build synonyms"}],"type":"illegal_argument_exception","reason":"Failed to build synonyms"},"status":400}

As per my analysis if I am adding some keywords in synonym file like for, of, end it gives me this error. For keywords like for, of I assume these might be English stopwords that might be conflicting with synonyms but don't understand why it breaks for **end** keyword in the synonym file. Can you please help with this one?

**Comment by navneet1v** [comment]
@aishwaryabajaj-54 not sure how this is related to k-NN plugin. You need to create a github issue in the main core repo here: https://github.com/opensearch-project/OpenSearch/issues I can more this issue to that repo too.

Let me know if there is any k-NN plugin related question here which I am missing.

**Comment by jmazanec15** [comment]
@aishwaryabajaj-54 is this related to k-NN index?

Seems like it is coming from https://github.com/opensearch-project/OpenSearch/blob/main/modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java#L160. Could you provide log message from here if you have it: https://github.com/opensearch-project/OpenSearch/blob/main/modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java#L159? Additionally, could you provide repro steps?

**Comment by jmazanec15** [comment]
Closing - believe not related to knn
